"""`wreath-hygiene` — borrowed credit and committed debris.

Two properties are worth more than the rest and are tested hardest: that it
catches the trailer that started this (a `Co-authored-by:` nobody asked for),
and that it does **not** fire on prose that merely mentions a tool. A gate with
false positives is a gate people delete, so half of these tests exist to hold
the second property rather than the first.

The module is importable with nothing installed — no `wreath` import, no
compiled extension — because CI runs it that way. `test_the_module_needs_no_
wreath_import` is what keeps that true.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

from wreath._devtools.hygiene import (
    check_message,
    check_paths,
    commit_messages,
    main,
    scan_commits,
    tracked_paths,
)

HYGIENE = Path(__file__).resolve().parents[1] / "src/wreath/_devtools/hygiene.py"


def _codes(findings) -> list[str]:
    return [f.code for f in findings]


# --- attribution: what must be caught -----------------------------------------


@pytest.mark.parametrize("trailer", [
    "Co-Authored-By: Claude <noreply@anthropic.com>",
    "Co-authored-by: Someone <a@b.c>",
    "co-authored-by: lowercase <a@b.c>",
    "Assisted-by: Some Tool",
    "Co-developed-by: A Model",
    "Generated-by: a harness",
])
def test_a_co_authorship_trailer_is_refused_however_it_is_spelled(trailer: str) -> None:
    """The exact defect this repository lost a week to, in every casing a
    harness emits. Matched case-insensitively because `Co-Authored-By` and
    `co-authored-by` are the same claim."""
    findings = check_message(f"fix: a real change\n\n{trailer}\n", where="c")
    assert "HYG001" in _codes(findings)


@pytest.mark.parametrize("notice", [
    "🤖 Generated with [Claude Code](https://claude.com/claude-code)",
    "Generated with Claude Code",
    "generated by ChatGPT",
    "Created with Copilot",
    "written by an AI",
    "Authored by a language model",
])
def test_a_generation_notice_is_refused(notice: str) -> None:
    findings = check_message(f"feat: something\n\n{notice}\n", where="c")
    assert "HYG002" in _codes(findings)


def test_a_bare_robot_emoji_is_refused_because_it_is_the_same_claim() -> None:
    """Most harnesses emit the emoji and drop the sentence."""
    assert "HYG002" in _codes(check_message("feat: x\n\n🤖\n", where="c"))


def test_one_message_reports_one_generation_finding_not_three() -> None:
    """Three regexes match "🤖 Generated with Claude"; a reviewer needs one line."""
    findings = check_message("x\n\n🤖 Generated with Claude Code\n", where="c")
    assert _codes(findings).count("HYG002") == 1


def test_the_finding_names_the_line_so_it_can_be_found() -> None:
    findings = check_message("subject\n\nbody\n\nCo-authored-by: X <a@b>\n", where="c")
    assert findings[0].where == "c:5"


# --- attribution: what must NOT be caught -------------------------------------
#
# A gate that cries wolf is a gate that gets deleted, so these matter as much as
# the ones above.


@pytest.mark.parametrize("innocent", [
    "feat(copilot): add a Copilot integration endpoint",
    "docs: explain how co-authorship trailers are handled",
    "fix: the claude.ai MCP connector times out",
    "refactor: rename the Gemini adapter",
    "test: cover the openai-compatible route",
    "docs: a paragraph about who generated the report, and by what",
])
def test_prose_that_merely_mentions_a_tool_is_not_a_claim_of_authorship(
    innocent: str,
) -> None:
    """Naming a vendor is not crediting one. The trailer regex is anchored to the
    start of a line and the generation regex needs a verb *and* a subject, which
    is what keeps `feat(copilot):` from being a finding."""
    assert check_message(innocent, where="c") == []


def test_a_trailer_shaped_string_mid_line_is_not_a_trailer() -> None:
    """`git` reads trailers at the start of a line; so does this."""
    assert check_message(
        "docs: describe the Co-authored-by: convention we refuse", where="c") == []


def test_a_clean_conventional_commit_passes() -> None:
    assert check_message(
        "feat(router): add a route\n\nBody explaining why.\n", where="c") == []


def test_scan_commits_reports_the_offending_sha() -> None:
    findings = scan_commits({
        "a" * 40: "clean: nothing here",
        "b" * 40: "bad: x\n\nCo-authored-by: Y <y@z>\n",
    })
    assert len(findings) == 1
    assert findings[0].where.startswith("commit bbbbbbbb")


# --- stray paths ---------------------------------------------------------------


@pytest.mark.parametrize("path", [
    ".pi/notes.md",
    "sub/.pi/notes.md",
    ".claude/settings.json",
    ".env",
    ".env.local",
    "scratch/experiment.py",
    "a/b/tmp/thing",
    "src/wreath/app.py.orig",
    "patch.rej",
    ".file.swp",
    "notes.md~",
    ".DS_Store",
    "nohup.out",
    "src/__pycache__/app.cpython-314.pyc",
    ".pytest_cache/v/cache/lastfailed",
    "htmlcov/index.html",
])
def test_debris_is_refused(path: str) -> None:
    assert _codes(check_paths([path])) == ["HYG010"]


@pytest.mark.parametrize("path", [
    ".env.example",                       # the committed template
    "src/wreath/_scaffold.py",
    "tests/test_hygiene.py",
    "docs/guides/infra.md",
    "scratchpad.py",                      # not the `scratch/` directory
    "src/wreath/_native/temporal.c",      # not the `temp/` directory
    ".github/workflows/ci.yml",
])
def test_ordinary_paths_pass(path: str) -> None:
    """`scratchpad.py` and `temporal.c` are the ones a sloppier pattern eats."""
    assert check_paths([path]) == []


def test_a_path_reports_one_finding_even_when_two_patterns_match() -> None:
    assert len(check_paths([".claude/__pycache__/x.pyc"])) == 1


# --- against this repository ---------------------------------------------------


def test_this_repository_is_currently_clean() -> None:
    """The gate has to pass on the tree it is being added to, or it is not a
    gate — it is a thing somebody disables on their first day."""
    root = Path(__file__).resolve().parents[1]
    assert check_paths(tracked_paths(root)) == []


def test_the_module_needs_no_wreath_import(tmp_path: Path) -> None:
    """CI runs this as a plain script behind `setup-python`, with no `uv sync`
    and no compiled extension. An `import wreath` here would cost the pipeline a
    27-second build, which is how a fast gate becomes a slow one nobody moves
    back."""
    result = subprocess.run(
        [sys.executable, str(HYGIENE), "--help"],
        capture_output=True, text=True, cwd=tmp_path,
        env={"PATH": "/usr/bin:/bin", "PYTHONPATH": ""},
    )
    assert result.returncode == 0, result.stderr
    assert "wreath-hygiene" in result.stdout


# --- the CLI, end to end through a real git repository -------------------------


def _repo(tmp_path: Path) -> Path:
    root = tmp_path / "repo"
    root.mkdir()
    run = lambda *a: subprocess.run(  # noqa: E731 - three uses, one line each
        ["git", *a], cwd=root, check=True, capture_output=True)
    run("init", "-q", "-b", "main")
    run("config", "user.email", "a@b.c")
    run("config", "user.name", "A")
    return root


def _commit(root: Path, name: str, message: str) -> None:
    (root / name).write_text("x", encoding="utf-8")
    subprocess.run(["git", "add", "-A"], cwd=root, check=True, capture_output=True)
    subprocess.run(["git", "commit", "-q", "-m", message],
                   cwd=root, check=True, capture_output=True)


def test_the_cli_fails_a_range_containing_a_trailer(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    root = _repo(tmp_path)
    _commit(root, "a.txt", "chore: base")
    _commit(root, "b.txt", "feat: thing\n\nCo-authored-by: Someone <s@x.y>\n")
    assert main(["--root", str(root), "--range", "HEAD~1..HEAD"]) == 1
    assert "HYG001" in capsys.readouterr().out


def test_the_cli_passes_a_clean_range(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    root = _repo(tmp_path)
    _commit(root, "a.txt", "chore: base")
    _commit(root, "b.txt", "feat: thing\n\nA body that explains why.\n")
    assert main(["--root", str(root), "--range", "HEAD~1..HEAD"]) == 0
    assert "0 finding(s)" in capsys.readouterr().out


def test_commit_messages_does_not_merge_two_commits_on_a_blank_line(
    tmp_path: Path,
) -> None:
    """A commit message contains blank lines by construction. Splitting the log
    on those attributes the second commit's body to the first, which reports a
    finding against a sha that is innocent."""
    root = _repo(tmp_path)
    # Three commits, so `HEAD~2` resolves: the range has to *exclude* a base,
    # and a two-commit repository has nothing before its root to exclude.
    _commit(root, "base.txt", "chore: base")
    _commit(root, "a.txt", "first: subject\n\nfirst body\n")
    _commit(root, "b.txt", "second: subject\n\nsecond body\n")
    messages = commit_messages(root, "HEAD~2..HEAD")
    assert len(messages) == 2
    assert [("first" in m) + ("second" in m) for m in messages.values()] == [1, 1]


def test_the_cli_flags_a_pull_request_body_as_hyg003(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    """A different code because the remedy differs: edit the description, rather
    than rewrite history."""
    root = _repo(tmp_path)
    _commit(root, "a.txt", "chore: base")
    body = tmp_path / "body.md"
    body.write_text("## What\n\n🤖 Generated with Claude Code\n", encoding="utf-8")
    assert main(["--root", str(root), "--message-file", str(body)]) == 1
    out = capsys.readouterr().out
    assert "HYG003" in out
    assert "HYG002" not in out


def test_the_cli_fails_a_tracked_stray_path(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    """`git add -f`, which is exactly how debris gets past `.gitignore`."""
    root = _repo(tmp_path)
    _commit(root, "a.txt", "chore: base")
    (root / ".pi").mkdir()
    (root / ".pi" / "notes.md").write_text("scratch", encoding="utf-8")
    subprocess.run(["git", "add", "-f", ".pi/notes.md"],
                   cwd=root, check=True, capture_output=True)
    subprocess.run(["git", "commit", "-q", "-m", "chore: oops"],
                   cwd=root, check=True, capture_output=True)
    assert main(["--root", str(root), "--paths"]) == 1
    assert "HYG010" in capsys.readouterr().out
