from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

from wreath._devtools.hygiene import (
    check_message,
    check_paths,
    commit_messages,
    main,
    scan_commits,
    tracked_paths,
)

HYGIENE = Path(__file__).resolve().parents[1] / "src/wreath/_devtools/hygiene.py"


def _codes(findings) -> list[str]:
    return [f.code for f in findings]


@pytest.mark.parametrize(
    "trailer",
    [
        "Co-Authored-By: Claude <noreply@anthropic.com>",
        "Co-authored-by: Someone <a@b.c>",
        "co-authored-by: lowercase <a@b.c>",
        "Assisted-by: Some Tool",
        "Co-developed-by: A Model",
        "Generated-by: a harness",
    ],
)
def test_a_co_authorship_trailer_is_refused_however_it_is_spelled(trailer: str) -> None:
    findings = check_message(f"fix: a real change\n\n{trailer}\n", where="c")
    assert "HYG001" in _codes(findings)


@pytest.mark.parametrize(
    "notice",
    [
        "🤖 Generated with [Claude Code](https://claude.com/claude-code)",
        "Generated with Claude Code",
        "generated by ChatGPT",
        "Created with Copilot",
        "written by an AI",
        "Authored by a language model",
    ],
)
def test_a_generation_notice_is_refused(notice: str) -> None:
    findings = check_message(f"feat: something\n\n{notice}\n", where="c")
    assert "HYG002" in _codes(findings)


def test_a_bare_robot_emoji_is_refused_because_it_is_the_same_claim() -> None:
    assert "HYG002" in _codes(check_message("feat: x\n\n🤖\n", where="c"))


def test_one_message_reports_one_generation_finding_not_three() -> None:
    findings = check_message("x\n\n🤖 Generated with Claude Code\n", where="c")
    assert _codes(findings).count("HYG002") == 1


def test_the_finding_names_the_line_so_it_can_be_found() -> None:
    findings = check_message("subject\n\nbody\n\nCo-authored-by: X <a@b>\n", where="c")
    assert findings[0].where == "c:5"


# A gate that cries wolf is a gate that gets deleted, so these matter as much as
# the ones above.


@pytest.mark.parametrize(
    "innocent",
    [
        "feat(copilot): add a Copilot integration endpoint",
        "docs: explain how co-authorship trailers are handled",
        "fix: the claude.ai MCP connector times out",
        "refactor: rename the Gemini adapter",
        "test: cover the openai-compatible route",
        "docs: a paragraph about who generated the report, and by what",
    ],
)
def test_prose_that_merely_mentions_a_tool_is_not_a_claim_of_authorship(
    innocent: str,
) -> None:
    assert check_message(innocent, where="c") == []


def test_a_trailer_shaped_string_mid_line_is_not_a_trailer() -> None:
    assert check_message("docs: describe the Co-authored-by: convention we refuse", where="c") == []


def test_a_clean_conventional_commit_passes() -> None:
    assert check_message("feat(router): add a route\n\nBody explaining why.\n", where="c") == []


def test_scan_commits_reports_the_offending_sha() -> None:
    findings = scan_commits(
        {
            "a" * 40: "clean: nothing here",
            "b" * 40: "bad: x\n\nCo-authored-by: Y <y@z>\n",
        }
    )
    assert len(findings) == 1
    assert findings[0].where.startswith("commit bbbbbbbb")


@pytest.mark.parametrize(
    "path",
    [
        ".pi/notes.md",
        "sub/.pi/notes.md",
        ".claude/settings.json",
        ".env",
        ".env.local",
        "scratch/experiment.py",
        "a/b/tmp/thing",
        "src/wreath/app.py.orig",
        "patch.rej",
        ".file.swp",
        "notes.md~",
        ".DS_Store",
        "nohup.out",
        "src/__pycache__/app.cpython-314.pyc",
        ".pytest_cache/v/cache/lastfailed",
        "htmlcov/index.html",
    ],
)
def test_debris_is_refused(path: str) -> None:
    assert _codes(check_paths([path])) == ["HYG010"]


@pytest.mark.parametrize(
    "path",
    [
        ".env.example",  # the committed template
        "src/wreath/_scaffold.py",
        "tests/test_hygiene.py",
        "scratchpad.py",  # not the `scratch/` directory
        "src/wreath/_native/temporal.c",  # not the `temp/` directory
        ".github/workflows/ci.yml",
    ],
)
def test_ordinary_paths_pass(path: str) -> None:
    assert check_paths([path]) == []


def test_a_path_reports_one_finding_even_when_two_patterns_match() -> None:
    assert len(check_paths([".claude/__pycache__/x.pyc"])) == 1


def test_this_repository_is_currently_clean() -> None:
    root = Path(__file__).resolve().parents[1]
    assert check_paths(tracked_paths(root)) == []


def test_the_module_needs_no_wreath_import(tmp_path: Path) -> None:
    result = subprocess.run(
        [sys.executable, str(HYGIENE), "--help"],
        capture_output=True,
        text=True,
        cwd=tmp_path,
        env={"PATH": "/usr/bin:/bin", "PYTHONPATH": ""},
    )
    assert result.returncode == 0, result.stderr
    assert "wreath-hygiene" in result.stdout


def _repo(tmp_path: Path) -> Path:
    root = tmp_path / "repo"
    root.mkdir()
    run = lambda *a: subprocess.run(  # noqa: E731 - three uses, one line each
        ["git", *a], cwd=root, check=True, capture_output=True
    )
    run("init", "-q", "-b", "main")
    run("config", "user.email", "a@b.c")
    run("config", "user.name", "A")
    return root


def _commit(root: Path, name: str, message: str) -> None:
    (root / name).write_text("x", encoding="utf-8")
    subprocess.run(["git", "add", "-A"], cwd=root, check=True, capture_output=True)
    subprocess.run(
        ["git", "commit", "-q", "-m", message], cwd=root, check=True, capture_output=True
    )


def test_the_cli_fails_a_range_containing_a_trailer(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    root = _repo(tmp_path)
    _commit(root, "a.txt", "chore: base")
    _commit(root, "b.txt", "feat: thing\n\nCo-authored-by: Someone <s@x.y>\n")
    assert main(["--root", str(root), "--range", "HEAD~1..HEAD"]) == 1
    assert "HYG001" in capsys.readouterr().out


def test_the_cli_passes_a_clean_range(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    root = _repo(tmp_path)
    _commit(root, "a.txt", "chore: base")
    _commit(root, "b.txt", "feat: thing\n\nA body that explains why.\n")
    assert main(["--root", str(root), "--range", "HEAD~1..HEAD"]) == 0
    assert "0 finding(s)" in capsys.readouterr().out


def test_commit_messages_does_not_merge_two_commits_on_a_blank_line(
    tmp_path: Path,
) -> None:
    root = _repo(tmp_path)
    # Three commits, so `HEAD~2` resolves: the range has to *exclude* a base,
    # and a two-commit repository has nothing before its root to exclude.
    _commit(root, "base.txt", "chore: base")
    _commit(root, "a.txt", "first: subject\n\nfirst body\n")
    _commit(root, "b.txt", "second: subject\n\nsecond body\n")
    messages = commit_messages(root, "HEAD~2..HEAD")
    assert len(messages) == 2
    assert [("first" in m) + ("second" in m) for m in messages.values()] == [1, 1]


def test_the_cli_flags_a_pull_request_body_as_hyg003(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    root = _repo(tmp_path)
    _commit(root, "a.txt", "chore: base")
    body = tmp_path / "body.md"
    body.write_text("## What\n\n🤖 Generated with Claude Code\n", encoding="utf-8")
    assert main(["--root", str(root), "--message-file", str(body)]) == 1
    out = capsys.readouterr().out
    assert "HYG003" in out
    assert "HYG002" not in out


def test_the_cli_fails_a_tracked_stray_path(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    root = _repo(tmp_path)
    _commit(root, "a.txt", "chore: base")
    (root / ".pi").mkdir()
    (root / ".pi" / "notes.md").write_text("scratch", encoding="utf-8")
    subprocess.run(["git", "add", "-f", ".pi/notes.md"], cwd=root, check=True, capture_output=True)
    subprocess.run(
        ["git", "commit", "-q", "-m", "chore: oops"], cwd=root, check=True, capture_output=True
    )
    assert main(["--root", str(root), "--paths"]) == 1
    assert "HYG010" in capsys.readouterr().out
