create table "camera_trap"."stations" ();
create table "camera_trap"."species" ();
create table "camera_trap"."assignments" ();
create table "camera_trap"."audit_entries" ();
create table "camera_trap"."sightings" ();
create table "camera_trap"."reserves" ();
create table "camera_trap"."cameras" ();
create table "camera_trap"."observers" ();
create table "camera_trap"."deployments" ();
alter table "camera_trap"."reserves" add column "name" text not null;
alter table "camera_trap"."cameras" add column "id" bigint not null;
alter table "camera_trap"."stations" add column "name" text not null;
alter table "camera_trap"."sightings" add column "tags" jsonb not null;
alter table "camera_trap"."audit_entries" add column "sighting_id" bigint not null;
alter table "camera_trap"."observers" add column "id" bigint not null;
alter table "camera_trap"."audit_entries" add column "at" timestamp with time zone not null;
alter table "camera_trap"."sightings" add column "thumbnail_key" text;
alter table "camera_trap"."cameras" add column "deployed_at" timestamp with time zone not null;
alter table "camera_trap"."deployments" add column "id" bigint not null;
alter table "camera_trap"."reserves" add column "area_hectares" integer not null;
alter table "camera_trap"."stations" add column "reserve_id" bigint not null;
alter table "camera_trap"."audit_entries" add column "action" text not null;
alter table "camera_trap"."assignments" add column "reserve_id" bigint not null;
alter table "camera_trap"."reserves" add column "created_at" timestamp with time zone not null;
alter table "camera_trap"."observers" add column "role" text not null;
alter table "camera_trap"."species" add column "common_name" text not null;
alter table "camera_trap"."observers" add column "reserve_id" bigint;
alter table "camera_trap"."deployments" add column "station_id" bigint not null;
alter table "camera_trap"."sightings" add column "confidence" smallint not null;
alter table "camera_trap"."sightings" add column "id" bigint not null;
alter table "camera_trap"."stations" add column "longitude" numeric not null;
alter table "camera_trap"."sightings" add column "camera_id" bigint not null;
alter table "camera_trap"."reserves" add column "timezone" text not null;
alter table "camera_trap"."cameras" add column "model" text not null;
alter table "camera_trap"."sightings" add column "identified_by" bigint;
alter table "camera_trap"."audit_entries" add column "id" bigint not null;
alter table "camera_trap"."species" add column "code" text not null;
alter table "camera_trap"."species" add column "scientific_name" text not null;
alter table "camera_trap"."assignments" add column "observer_id" bigint not null;
alter table "camera_trap"."sightings" add column "deployment_id" bigint;
alter table "camera_trap"."cameras" add column "station_id" bigint not null;
alter table "camera_trap"."sightings" add column "captured_at" timestamp with time zone not null;
alter table "camera_trap"."species" add column "id" bigint not null;
alter table "camera_trap"."sightings" add column "uploaded_at" timestamp with time zone not null;
alter table "camera_trap"."sightings" add column "image_key" text not null;
alter table "camera_trap"."sightings" add column "notes" text;
alter table "camera_trap"."sightings" add column "species_id" bigint not null;
alter table "camera_trap"."reserves" add column "slug" text not null;
alter table "camera_trap"."cameras" add column "battery_pct" smallint not null;
alter table "camera_trap"."cameras" add column "serial" text not null;
alter table "camera_trap"."stations" add column "latitude" numeric not null;
alter table "camera_trap"."species" add column "protection" text not null;
alter table "camera_trap"."sightings" add column "review_state" text not null;
alter table "camera_trap"."stations" add column "sensitive" boolean not null;
alter table "camera_trap"."observers" add column "email" text not null;
alter table "camera_trap"."deployments" add column "card_serial" text not null;
alter table "camera_trap"."reserves" add column "id" bigint not null;
alter table "camera_trap"."cameras" add column "retired_at" timestamp with time zone;
alter table "camera_trap"."stations" add column "id" bigint not null;
alter table "camera_trap"."species" add column "nocturnal" boolean not null;
alter table "camera_trap"."audit_entries" add column "observer_id" bigint not null;
alter table "camera_trap"."deployments" add column "ingested_at" timestamp with time zone;
alter table "camera_trap"."stations" add column "habitat" text not null;
alter table "camera_trap"."deployments" add column "image_count" integer not null;
alter table "camera_trap"."cameras" add column "firmware" text not null;
alter table "camera_trap"."sightings" add column "station_id" bigint not null;
alter table "camera_trap"."deployments" add column "collected_at" timestamp with time zone not null;
alter table "camera_trap"."assignments" add column "level" text not null;
alter table "camera_trap"."observers" add column "display_name" text not null;
alter table "camera_trap"."sightings" add constraint "wreath_2303c15eb5602a9a" primary key ("id");
alter table "camera_trap"."observers" add constraint "wreath_26fea6258c4c3e3b" unique ("email");
alter table "camera_trap"."cameras" add constraint "wreath_486e04939350b1c6" unique ("serial");
alter table "camera_trap"."species" add constraint "wreath_48a96531b33c71e5" unique ("code");
alter table "camera_trap"."reserves" add constraint "wreath_527420a77e2b9ea8" unique ("slug");
alter table "camera_trap"."deployments" add constraint "wreath_6cdb10234fedcd36" primary key ("id");
alter table "camera_trap"."species" add constraint "wreath_71043dcc5a86f70c" primary key ("id");
alter table "camera_trap"."reserves" add constraint "wreath_7d22dea5a111a04f" primary key ("id");
alter table "camera_trap"."audit_entries" add constraint "wreath_7f5694a3da0ff72e" unique ("observer_id", "sighting_id", "at");
alter table "camera_trap"."cameras" add constraint "wreath_893d4760749e198e" primary key ("id");
alter table "camera_trap"."audit_entries" add constraint "wreath_95cd5611cae6442e" primary key ("id");
alter table "camera_trap"."stations" add constraint "wreath_a787d64e2c928a7b" primary key ("id");
alter table "camera_trap"."observers" add constraint "wreath_e7857d4e8f22b57f" primary key ("id");
alter table "camera_trap"."assignments" add constraint "wreath_f085195025b3e227" primary key ("observer_id", "reserve_id");
create index "wreath_0b894d4a5ca84d03" on "camera_trap"."audit_entries" ("observer_id");
create index "wreath_17bbb28e11831755" on "camera_trap"."cameras" ("station_id", "deployed_at") where (retired_at IS NULL);
create index "wreath_2f7b9a56d0a18562" on "camera_trap"."sightings" ("camera_id");
create index "wreath_3beb3dadca332db6" on "camera_trap"."stations" ("reserve_id", "id") where (sensitive = true);
create index "wreath_523012549caeed63" on "camera_trap"."sightings" ("station_id", "captured_at");
create index "wreath_6044f03a11cb3b45" on "camera_trap"."assignments" ("reserve_id", "level");
create index "wreath_6f66df50ccb2c7a7" on "camera_trap"."sightings" ("species_id");
create index "wreath_7489c8ca792fc97d" on "camera_trap"."cameras" ("station_id");
create index "wreath_8cdfe6906bae2c1a" on "camera_trap"."sightings" ("deployment_id");
create index "wreath_92ab428c7f777e6d" on "camera_trap"."species" ("protection", "id") where (protection = ANY (ARRAY['sensitive'::text, 'restricted'::text]));
create index "wreath_97549b2afbffc675" on "camera_trap"."deployments" ("station_id");
create index "wreath_a38fba66cd33258d" on "camera_trap"."sightings" ("station_id");
create index "wreath_d1006d8f04327f48" on "camera_trap"."sightings" ("station_id", "captured_at") where (review_state = 'needs-review'::text);
create index "wreath_e268bd7e0cc134d1" on "camera_trap"."deployments" ("station_id", "collected_at") where (ingested_at IS NULL);
create index "wreath_e26c2e928caa6c5c" on "camera_trap"."stations" ("reserve_id");
create index "wreath_f0694d738eaa9993" on "camera_trap"."sightings" ("captured_at");
alter table "camera_trap"."assignments" add constraint "wreath_023c045f57791e78" foreign key ("reserve_id") references "camera_trap"."reserves" ("id");
alter table "camera_trap"."sightings" add constraint "wreath_09c6c60ec98328dd" foreign key ("identified_by") references "camera_trap"."observers" ("id");
alter table "camera_trap"."assignments" add constraint "wreath_0c8d7ac367ee4de2" foreign key ("observer_id") references "camera_trap"."observers" ("id");
alter table "camera_trap"."sightings" add constraint "wreath_211a48f62baa7e68" foreign key ("deployment_id") references "camera_trap"."deployments" ("id");
alter table "camera_trap"."deployments" add constraint "wreath_292b6ec00817b232" foreign key ("station_id") references "camera_trap"."stations" ("id");
alter table "camera_trap"."sightings" add constraint "wreath_2d171e90d0e22208" foreign key ("camera_id") references "camera_trap"."cameras" ("id");
alter table "camera_trap"."stations" add constraint "wreath_44d07acbfee164c1" foreign key ("reserve_id") references "camera_trap"."reserves" ("id");
alter table "camera_trap"."cameras" add constraint "wreath_5d113306d8b59c3a" foreign key ("station_id") references "camera_trap"."stations" ("id");
alter table "camera_trap"."sightings" add constraint "wreath_6108791da55aa5e1" foreign key ("species_id") references "camera_trap"."species" ("id");
alter table "camera_trap"."observers" add constraint "wreath_8f6edff4cdcacc75" foreign key ("reserve_id") references "camera_trap"."reserves" ("id");
alter table "camera_trap"."audit_entries" add constraint "wreath_9437634cdafad3b4" foreign key ("sighting_id") references "camera_trap"."sightings" ("id");
alter table "camera_trap"."audit_entries" add constraint "wreath_ac280301c2077168" foreign key ("observer_id") references "camera_trap"."observers" ("id");
alter table "camera_trap"."sightings" add constraint "wreath_ea604496651c2196" foreign key ("station_id") references "camera_trap"."stations" ("id");
