"""Generate `wreath._capability_data`, the index `wreath capabilities` reads.

`docs/agents/manifest.json` is the map, and it stays the map. But it lives under
`docs/`, which is not in the wheel, and the reader this command exists for --
somebody who typed `pip install wreath` and arrived knowing the word `celery` --
has no checkout to read it from. So the two fields that answer that reader
(`capability` and `replaces`) are compiled into a module inside the package.

That is a derived artifact, and a derived artifact with no staleness check is a
map that rots -- which is the exact failure `wreath-map-lint` exists to prevent,
so the check lives there too (`MAP015`) and `--fix` regenerates. The comparison
is byte for byte rather than value for value, so a hand edit to the generated
file fails in the same place a missed regeneration does; there is no way to
change the shipped answer except by changing the manifest.

Only the fields a *reader* needs are carried over. `policy`, `tests`, and
`decisions` are for somebody working on this repository, they are most of the
manifest's 190 KB, and none of them would ever be printed.
"""

from __future__ import annotations

import json
from pathlib import Path

from .._docs.capabilities import public_modules

__all__ = ["DATA_MODULE", "MANIFEST", "render_module", "rows", "write_module"]

#: Where the generated module lives, relative to the repository root.
DATA_MODULE = "src/wreath/_capability_data.py"

MANIFEST = "docs/agents/manifest.json"

_HEADER = '''"""The capability index, generated from `docs/agents/manifest.json`.

**Do not edit this file.** Change the manifest and run
`uv run wreath-map-lint --fix`; `MAP015` fails while the two disagree, and the
comparison is byte for byte, so an edit here is a gate failure rather than a
change to what `wreath capabilities` answers.

It exists because the manifest is under `docs/` and the wheel is not, and the
reader this serves has installed wreath rather than cloned it. See
`wreath._devtools.capability_index` for what is carried over and why.
"""

from __future__ import annotations

__all__ = ["ROWS"]

#: One entry per subsystem that has a user-facing capability, in manifest order
#: -- which already runs roughly the way the docs nav does: handling a request,
#: then data, then auth, then background work, then operations.
ROWS: tuple[dict[str, str | tuple[str, ...]], ...] = (
'''

_FOOTER = ")\n"


def rows(manifest: dict) -> list[dict[str, object]]:
    """The manifest's subsystems as the index carries them, in manifest order.

    A subsystem whose `capability` is `null` is implementation rather than a
    surface a reader can reach for, and contributes nothing: answering somebody's
    search with a row they cannot use is worse than not answering it.
    """
    carried: list[dict[str, object]] = []
    for subsystem in manifest.get("subsystems", []):
        capability = subsystem.get("capability")
        if not capability:
            continue
        carried.append(
            {
                "name": str(subsystem.get("name", "")),
                "capability": str(capability),
                "modules": tuple(public_modules(subsystem.get("sources", ()))),
                "guides": tuple(str(guide) for guide in subsystem.get("guides", ())),
                # Lower-cased once here rather than on every lookup: these are
                # distribution names, which PyPI matches case-insensitively, and
                # a reader types whichever case they remember.
                "replaces": tuple(
                    str(name).strip().lower()
                    for name in subsystem.get("replaces") or ()
                    if str(name).strip()
                ),
            }
        )
    return carried


def render_module(manifest: dict) -> str:
    """The whole generated module as text, deterministically."""
    body = "".join(_render_row(row) for row in rows(manifest))
    return f"{_HEADER}{body}{_FOOTER}"


def write_module(root: Path, manifest: dict | None = None) -> bool:
    """Rewrite the generated module. Returns whether anything changed."""
    if manifest is None:
        manifest = json.loads((root / MANIFEST).read_text(encoding="utf-8"))
    path = root / DATA_MODULE
    rendered = render_module(manifest)
    if path.exists() and path.read_text(encoding="utf-8") == rendered:
        return False
    path.write_text(rendered, encoding="utf-8")
    return True


def _render_row(row: dict[str, object]) -> str:
    fields = "".join(
        f"        {key!r}: {_literal(row[key])},\n"
        for key in ("name", "capability", "modules", "guides", "replaces")
    )
    return f"    {{\n{fields}    }},\n"


def _literal(value: object) -> str:
    """A `repr` that spells a one-element tuple with its trailing comma.

    `repr(("a",))` already does, but going through here keeps the rendering of
    every field in one place rather than trusting two spellings to agree.
    """
    if isinstance(value, tuple):
        inner = ", ".join(repr(item) for item in value)
        return f"({inner},)" if len(value) == 1 else f"({inner})"
    return repr(value)
