// A realistic consumer of the generated client and hooks. Compiled under
// TypeScript strict mode to prove the generated surface is well-typed. The
// generated files are produced into ./generated by the compile test.
import * as React from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

import { createWreathClient, WreathApiError } from "./generated/client";
import type { Item, ItemPage } from "./generated/models";
import {
  WreathClientProvider,
  useGetItem,
  useGetItems,
  useCreateItem,
} from "./generated/react-query";

const client = createWreathClient({
  baseUrl: "https://api.example.com",
  headers: async () => ({ authorization: "Bearer token" }),
});

export function ItemView({ id }: { id: number }): React.ReactElement {
  const item = useGetItem({ itemId: id, expand: true });
  const list: ReturnType<typeof useGetItems> = useGetItems({ limit: 10 });
  const create = useCreateItem();

  if (item.isError) {
    const error: WreathApiError = item.error;
    return <div>Error {error.status}</div>;
  }
  const page: ItemPage | undefined = list.data;
  const value: Item | undefined = item.data;
  return (
    <button
      onClick={() =>
        create.mutate({
          name: "widget",
          price: 1,
          priority: "high",
          kind: "basic",
          tags: [],
          metadata: {},
        })
      }
    >
      {value?.name ?? "?"} of {page?.total ?? 0}
    </button>
  );
}

export function App(): React.ReactElement {
  const queryClient = new QueryClient();
  return (
    <QueryClientProvider client={queryClient}>
      <WreathClientProvider value={client}>
        <ItemView id={1} />
      </WreathClientProvider>
    </QueryClientProvider>
  );
}

// Direct client usage (no React) to prove the transport surface types.
export async function loadItem(): Promise<Item> {
  return client.getItem({ itemId: 42, expand: false, traceId: "abc" });
}
