/* wreath._native._core: hand-written C accelerators for Wreath's hot paths.
 *
 * Required: `wreath._native` refuses at import without this module. The facades
 * in wreath.* bind straight to what they need here.
 */
#include "wreathcore.h"


static PyObject *
wreath_decode_json_validation_tape(PyObject *Py_UNUSED(self), PyObject *args)
{
    PyObject *data;
    PyObject *plan;
    PyObject *loc;
    PyObject *payload;
    PyObject *validation_args;
    PyObject *result;

    if (!PyArg_UnpackTuple(
            args, "decode_json_validation_tape", 3, 3, &data, &plan, &loc)) {
        return NULL;
    }
    result = wreath_json_loads_validation(data, plan, loc);
    if (result == NULL) {
        return NULL;
    }
    if (result != Py_NotImplemented) {
        return result;
    }
    Py_DECREF(result);
    payload = wreath_json_loads(NULL, data);
    if (payload == NULL) {
        return NULL;
    }
    validation_args = PyTuple_Pack(3, plan, payload, loc);
    Py_DECREF(payload);
    if (validation_args == NULL) {
        return NULL;
    }
    result = wreath_run_validation(NULL, validation_args);
    Py_DECREF(validation_args);
    return result;
}


static PyMethodDef core_methods[] = {
    {"activate_path", wreath_activate_path, METH_VARARGS,
     "activate_path(params, plan) -> (kwargs, errors)\n"
     "Execute a startup-compiled path-scalar binding plan."},
    {"bind_path_into",
     (PyCFunction)(void (*)(void))wreath_bind_path_into, METH_FASTCALL,
     "bind_path_into(params, plan, kwargs) -> errors | None\n"
     "Populate an existing mixed-source binding without success allocations."},
    {"activate_path_call",
     (PyCFunction)(void (*)(void))wreath_activate_path_call, METH_FASTCALL,
     "activate_path_call(handler, request, plan, error_type) -> result\n"
     "Activate path scalars and vectorcall the handler."},
    {"request_layout", wreath_request_layout, METH_O,
     "Compile one operation-owned exact Request slot layout."},
    {"request_new", (PyCFunction)(void (*)(void))wreath_request_new,
     METH_FASTCALL,
     "Materialize one exact Request at the handler-activation boundary."},
    {"parse_dotenv", wreath_parse_dotenv, METH_O,
     "parse_dotenv(data) -> dict[str, str]"},
    {"read_osenv", wreath_read_osenv, METH_NOARGS,
     "read_osenv() -> dict[str, str]"},
    {"cache_key_selected", wreath_cache_key_selected, METH_VARARGS,
     "cache_key_selected(method, path, query, declared) -> str"},
    {"validate_bit_string",
     (PyCFunction)(void (*)(void))wreath_validate_bit_string, METH_FASTCALL,
     "validate_bit_string(value, expected_length) -> value"},
    {"float_sequence", wreath_float_sequence, METH_VARARGS,
     "float_sequence(values, dimension, half) -> list[float]"},
    {"array_coerce", wreath_array_coerce, METH_VARARGS,
     "array_coerce(values, nullable, name, oid, coerce) -> list"},
    {"map_nullable", wreath_map_nullable, METH_VARARGS,
     "map_nullable(values, function) -> list"},
    {"sparsevector_parts", wreath_sparsevector_parts, METH_VARARGS,
     "sparsevector_parts(dimension, elements, max_nnz) -> (indices, values)"},
    {"sparsevector_data", wreath_sparsevector_data, METH_VARARGS,
     "Compile a SparseVector into immutable native storage."},
    {"sparsevector_dim", wreath_sparsevector_dim, METH_O,
     "Return the dimension of native sparse-vector storage."},
    {"sparsevector_len", wreath_sparsevector_len, METH_O,
     "Return the non-zero count of native sparse-vector storage."},
    {"sparsevector_indices", wreath_sparsevector_indices, METH_O,
     "Materialize sparse-vector indices at the Python boundary."},
    {"sparsevector_values", wreath_sparsevector_values, METH_O,
     "Materialize sparse-vector values at the Python boundary."},
    {"sparsevector_dict", wreath_sparsevector_dict, METH_O,
     "Materialize sparse-vector items at the Python boundary."},
    {"sparsevector_equal", wreath_sparsevector_equal, METH_VARARGS,
     "Compare two native sparse-vector values."},
    {"sparsevector_hash", wreath_sparsevector_hash, METH_O,
     "Hash native sparse-vector storage without materializing cells."},
    {"cookie_header", wreath_cookie_header, METH_VARARGS,
     "Build and validate one Set-Cookie header value."},
    {"log_batch", wreath_log_batch, METH_VARARGS,
     "Materialize a log page at its public Batch boundary."},
    {"local_walk", wreath_local_walk, METH_VARARGS,
     "local_walk(root, scandir, join) -> sorted object keys"},
    {"recurrence_plan", wreath_recurrence_plan, METH_VARARGS,
     "Prepare immutable calendar-recurrence masks."},
    {"recurrence_next", wreath_recurrence_next, METH_VARARGS,
     "Find the next matching local-wall-clock recurrence."},
    {"attempt_encode", wreath_attempt_encode, METH_VARARGS,
     "Encode one complete job-attempt record."},
    {"attempt_decode", wreath_attempt_decode, METH_VARARGS,
     "Decode and materialize one complete job-attempt record."},
    {"sigv4_headers", wreath_sigv4_headers, METH_O,
     "Canonicalize SigV4 headers and their signed-name list."},
    {"sigv4_canonical", wreath_sigv4_canonical, METH_VARARGS,
     "Build one AWS Signature Version 4 canonical request."},
    {"zip_entry_count", wreath_zip_entry_count, METH_VARARGS,
     "Count bounded ZIP central-directory records without materializing them."},
    {"http_exchange_encode", wreath_http_exchange_encode, METH_VARARGS,
     "Encode one complete outbound HTTP replay exchange."},
    {"http_exchange_decode", wreath_http_exchange_decode, METH_VARARGS,
     "Decode one complete outbound HTTP replay exchange."},
    {"gzip_encoder_new", wreath_gzip_encoder_new, METH_NOARGS,
     "Allocate application-owned reusable gzip encoder workspace."},
    {"gzip_format", wreath_gzip_format, METH_O,
     "Classify one content type for the format-aware gzip encoder."},
    {"gzip_compress", (PyCFunction)(void (*)(void))wreath_gzip_compress, METH_FASTCALL,
     "gzip_compress(data, level, format) -> RFC 1952 member."},
    {"gzip_compress_with", (PyCFunction)(void (*)(void))wreath_gzip_compress_with,
     METH_FASTCALL,
     "gzip_compress_with(workspace, data, level, format) -> RFC 1952 member."},
    {"gzip_fragment_compress_with",
     (PyCFunction)(void (*)(void))wreath_gzip_fragment_compress_with,
     METH_FASTCALL,
     "gzip_fragment_compress_with(workspace, data, level, format, fragments)."},
    {"gzip_decoder_new", wreath_gzip_decoder_new, METH_NOARGS,
     "Allocate stream-owned reusable gzip decoder workspace."},
    {"gzip_decompress", (PyCFunction)(void (*)(void))wreath_gzip_decompress,
     METH_FASTCALL,
     "gzip_decompress(data, max_output_bytes, format) -> bytes."},
    {"gzip_decompress_with", (PyCFunction)(void (*)(void))wreath_gzip_decompress_with,
     METH_FASTCALL,
     "gzip_decompress_with(workspace, data, max_output_bytes, format) -> bytes."},
    {"gzip_codec_info", wreath_gzip_codec_info, METH_NOARGS,
     "Identify the independent native gzip kernels."},
    {"first_duplicate", wreath_first_duplicate, METH_O,
     "Return the first repeated item in a sequence, or None."},
    {"minimal_prefixes", wreath_minimal_prefixes, METH_O,
     "Sort strings and retain only shortest covering prefixes."},
    {"fused_order", wreath_fused_order, METH_VARARGS,
     "Rank keys by reciprocal-rank fusion."},
    {"rank_indices", wreath_rank_indices, METH_VARARGS,
     "Select one page of numeric-score indices."},
    {"normalise_argument", wreath_normalise_argument, METH_VARARGS,
     "Normalise one bounded argument directly to JSON text."},
    {"transport_decode_parts", wreath_transport_decode_parts, METH_VARARGS,
     "Decode transport-recording data fields."},
    {"fault_encode_parts", wreath_fault_encode_parts, METH_VARARGS,
     "Encode replay fault data fields."},
    {"fault_decode_parts", wreath_fault_decode_parts, METH_VARARGS,
     "Decode replay fault data fields."},
    {"dns_parse_txt", wreath_dns_parse_txt, METH_VARARGS,
     "Decode TXT records from one DNS response."},
    {"siphash24", wreath_siphash24, METH_VARARGS,
     "Compute a SipHash-2-4 fingerprint over one byte buffer."},
    {"log_cell_encode", wreath_log_cell_encode, METH_VARARGS,
     "Encode one native-flight log cell."},
    {"log_cell_decode", wreath_log_cell_decode, METH_VARARGS,
     "Decode one native-flight log cell."},
    {"capture_slab_decode", wreath_capture_slab_decode, METH_VARARGS,
     "Decode one native-flight capture slab."},
    {"step_encode", wreath_step_encode, METH_VARARGS,
     "Encode one workflow-step recording."},
    {"step_decode", wreath_step_decode, METH_VARARGS,
     "Decode one workflow-step recording."},
    {"metrics_flatten", wreath_metrics_flatten, METH_VARARGS,
     "Flatten counter readings with native key and integer ownership."},
    {"locale_preference", wreath_locale_preference, METH_O,
     "Select the preferred language from an Accept-Language value."},
    {"select_language", wreath_select_language, METH_VARARGS,
     "Select an offered language from an Accept-Language value."},
    {"normalize_host", wreath_normalize_host, METH_VARARGS,
     "Normalize one HTTP Host authority or trusted-host pattern."},
    {"forwarded_proto", wreath_forwarded_proto, METH_O,
     "Read the first valid X-Forwarded-Proto value."},
    {"forwarded_host", wreath_forwarded_host, METH_O,
     "Read the first non-empty X-Forwarded-Host value."},
    {"parse_accept", wreath_parse_accept, METH_O,
     "Parse and rank one HTTP Accept value."},
    {"negotiate_media", wreath_negotiate_media, METH_VARARGS,
     "Choose an offered media type from one HTTP Accept value."},
    {"bearer_token", wreath_bearer_token, METH_O,
     "Extract one unambiguous Bearer credential from ASGI headers."},
    {"cacheable_headers", wreath_cacheable_headers, METH_O,
     "Check response headers for shared-cache exclusions."},
    {"sync_version", wreath_sync_version, METH_O,
     "Hash one sync row mapping into its stable version string."},
    {"sync_state", wreath_sync_state, METH_O,
     "Compile materialized sync rows into request-owned native state."},
    {"sync_state_diff", wreath_sync_state_diff, METH_VARARGS,
     "Diff materialized rows against request-owned native sync state."},
    {"sync_state_keys", wreath_sync_state_keys, METH_O,
     "Materialize the keys in request-owned native sync state."},
    {"sync_state_size", wreath_sync_state_size, METH_O,
     "Return the number of rows in request-owned native sync state."},
    {"run_validation", wreath_run_validation, METH_VARARGS,
     "run_validation(plan, value, loc) -> (result, errors)"},
    {"compile_validation_plan", wreath_compile_validation_plan, METH_O,
     "Compile a Python declaration tape into an operation-owned native plan."},
    {"run_validation_json", wreath_run_validation_json, METH_VARARGS,
     "run_validation_json(plan, value, loc) -> (body | None, errors)\n"
     "Validate a response value and serialize its successful JSON form."},
    {"decode_json_validation_tape", wreath_decode_json_validation_tape, METH_VARARGS,
     "decode_json_validation_tape(data, plan, loc) -> (result, errors)"},
    {"orm_shape", wreath_orm_shape, METH_VARARGS,
     "orm_shape(registry, select) -> bytes\nORM query cache key."},
    {"orm_shape_configure", wreath_orm_shape_configure, METH_VARARGS,
     "orm_shape_configure(*expr_types, ORMError) -> None"},
    {"orm_relationship_keys", wreath_orm_relationship_keys, METH_VARARGS,
     "Group parents by loaded relationship key and initialize relation slots."},
    {"orm_attach_relationships", wreath_orm_attach_relationships, METH_VARARGS,
     "Attach a hydrated child batch to grouped parents."},
    {"orm_compile_hydrate_plan", wreath_orm_compile_hydrate_plan, METH_VARARGS,
     "Compile cached row and join constants into a reusable native plan."},
    {"orm_hydrate_records", wreath_orm_hydrate_records, METH_VARARGS,
     "Hydrate a record batch and assemble its joined relationships."},
    {"orm_collect_values", wreath_orm_collect_values, METH_VARARGS,
     "orm_collect_values(select) -> list[ValueExpr]\nBind nodes in order."},
    {"csrf_sign", wreath_csrf_sign, METH_VARARGS,
     "csrf_sign(secret, issued, nonce) -> str"},
    {"random_hex", wreath_random_hex, METH_VARARGS,
     "random_hex(size) -> str"},
    {"csrf_new_token", wreath_csrf_new_token, METH_VARARGS,
     "csrf_new_token(secret, issued) -> str"},
    {"csrf_validate", wreath_csrf_validate, METH_VARARGS,
     "csrf_validate(secret, token, now, max_age) -> (bool, int)"},
    {"host_allowed", wreath_host_allowed, METH_VARARGS,
     "host_allowed(host, patterns) -> bool"},
    {"jose_b64url_decode", wreath_jose_b64url_decode, METH_O,
     "jose_b64url_decode(data) -> bytes\nStrict unpadded URL-safe base64 decode."},
    {"jose_parse", wreath_jose_parse, METH_VARARGS,
     "jose_parse(token, max_segment_bytes) -> (header, payload, signing_input, signature)"},
    {"jose_verify_hs", wreath_jose_verify_hs, METH_VARARGS,
     "jose_verify_hs(digestmod, key, signing_input, signature) -> bool"},
    {"jose_verify_rsa", wreath_jose_verify_rsa, METH_VARARGS,
     "jose_verify_rsa(n, e, key_bytes, hash, digest, signature, pss) -> bool"},
    {"jose_validate_claims", wreath_jose_validate_claims, METH_VARARGS,
     "jose_validate_claims(claims, now, leeway, issuer, audiences, required) -> int"},
    {"cedar_to_value", wreath_cedar_to_value, METH_VARARGS,
     "cedar_to_value(value, EntityUid, Mapping, where) -> compiled value"},
    {"graphql_new_results", wreath_graphql_new_results, METH_O,
     "graphql_new_results(instances) -> result builder"},
    {"graphql_finish_results", wreath_graphql_finish_results, METH_O,
     "graphql_finish_results(builder) -> list[dict]"},
    {"graphql_project_plain", wreath_graphql_project_plain, METH_VARARGS,
     "graphql_project_plain(instances, schema_fields, fields) -> list[dict] | None"},
    {"graphql_project_constant", wreath_graphql_project_constant, METH_VARARGS,
     "graphql_project_constant(results, key, value) -> None"},
    {"graphql_project_attribute", wreath_graphql_project_attribute, METH_VARARGS,
     "graphql_project_attribute(results, instances, key, attribute) -> None"},
    {"graphql_project_values", wreath_graphql_project_values, METH_VARARGS,
     "graphql_project_values(results, key, values) -> None"},
    {"graphql_flatten_values", wreath_graphql_flatten_values, METH_VARARGS,
     "graphql_flatten_values(values, is_list) -> (flat, layout)"},
    {"graphql_flatten_relationship", wreath_graphql_flatten_relationship, METH_VARARGS,
     "graphql_flatten_relationship(instances, relation_index, is_list) -> (flat, layout)"},
    {"graphql_restore_layout", wreath_graphql_restore_layout, METH_VARARGS,
     "graphql_restore_layout(results, key, projected, layout, is_list) -> None"},
    {"graphql_restore_values", wreath_graphql_restore_values, METH_VARARGS,
     "graphql_restore_values(projected, layout, is_list) -> list"},
    {"graphql_parse", wreath_graphql_parse, METH_VARARGS,
     "graphql_parse(source, limits, config) -> Document"},
    {"graphql_policy_schema", wreath_graphql_policy_schema, METH_VARARGS,
     "Compile immutable GraphQL policy resources."},
    {"graphql_policy_state", wreath_graphql_policy_state, METH_O,
     "Create request-owned GraphQL policy decisions."},
    {"graphql_policy_prepare", wreath_graphql_policy_prepare, METH_VARARGS,
     "Prepare one selected GraphQL policy projection."},
    {"graphql_policy_resources", wreath_graphql_policy_resources, METH_O,
     "Materialize pending resources at an authorizer boundary."},
    {"graphql_policy_items", wreath_graphql_policy_items, METH_VARARGS,
     "Materialize pending resource paths at a scalar authorizer boundary."},
    {"graphql_policy_apply", wreath_graphql_policy_apply, METH_VARARGS,
     "Apply authorizer decisions to request-owned GraphQL policy state."},
    {"graphql_policy_result", wreath_graphql_policy_result, METH_VARARGS,
     "Return root/projection policy bits for one selection."},
    {"graphql_policy_cached", wreath_graphql_policy_cached, METH_VARARGS,
     "Read one request-owned GraphQL policy decision."},
    {"graphql_policy_store", wreath_graphql_policy_store, METH_VARARGS,
     "Store one request-owned GraphQL policy decision."},
    {"graphql_policy_resource", wreath_graphql_policy_resource, METH_VARARGS,
     "Materialize one compiled resource at an authorizer boundary."},
    {"flight_project_cells", wreath_flight_project_cells, METH_VARARGS,
     "Decode and dispatch one drained flight-cell batch."},
    {"flight_settle", wreath_flight_settle, METH_VARARGS,
     "Settle completed flight assemblies and count orphaned tails."},
    {"flight_evict_pending", wreath_flight_evict_pending, METH_VARARGS,
     "Evict and account for the oldest pending flight assembly."},
    {"flight_metadata_bytes", wreath_flight_metadata_bytes, METH_VARARGS,
     "flight_metadata_bytes(image, SchemaError) -> canonical bytes"},
    {"flight_metadata_decode", wreath_flight_metadata_decode, METH_VARARGS,
     "flight_metadata_decode(data, types, SchemaError, max_chunk, max_rows, version)"},
    {"signature_parse_dictionary", wreath_signature_parse_dictionary, METH_VARARGS,
     "Parse the RFC 8941 dictionaries used by HTTP Message Signatures."},
    {"signature_parse_string", wreath_signature_parse_string, METH_VARARGS,
     "Parse one RFC 8941 quoted string."},
    {"signature_compile_pair", wreath_signature_compile_pair, METH_VARARGS,
     "Compile paired Signature-Input and Signature fields into a native plan."},
    {"signature_plan_facts", wreath_signature_plan_facts, METH_O,
     "Materialize verification facts from a native signature plan."},
    {"signature_plan_base", wreath_signature_plan_base, METH_VARARGS,
     "Construct an RFC 9421 signature base from a native plan."},
    {"signature_base", wreath_signature_base, METH_VARARGS,
     "Construct an RFC 9421 signature base."},
    {"curve_ed_add", wreath_curve_ed_add, METH_VARARGS,
     "Add two edwards25519 points."},
    {"curve_ed_negate", wreath_curve_ed_negate, METH_VARARGS,
     "Negate an edwards25519 point."},
    {"curve_ed_equal", wreath_curve_ed_equal, METH_VARARGS,
     "Compare two edwards25519 points projectively."},
    {"curve_ed_scalar", wreath_curve_ed_scalar, METH_VARARGS,
     "Multiply an edwards25519 point by a scalar."},
    {"curve_ed_double_scalar", wreath_curve_ed_double_scalar, METH_VARARGS,
     "Compute an edwards25519 double-scalar multiplication."},
    {"curve_ed_recover_x", wreath_curve_ed_recover_x, METH_VARARGS,
     "Recover an edwards25519 x coordinate."},
    {"curve_ed_decode", wreath_curve_ed_decode, METH_VARARGS,
     "Decode an RFC 8032 point."},
    {"curve_ed_encode", wreath_curve_ed_encode, METH_VARARGS,
     "Encode an RFC 8032 point."},
    {"curve_ed_verify", wreath_curve_ed_verify, METH_VARARGS,
     "Verify an Ed25519 equation from its SHA-512 challenge."},
    {"curve_ed_public_key", wreath_curve_ed_public_key, METH_O,
     "Derive an RFC 8032 public key from a 32-byte seed."},
    {"curve_ed_sign", wreath_curve_ed_sign, METH_VARARGS,
     "Sign a message with an RFC 8032 seed."},
    {"curve_p256_on_curve", wreath_curve_p256_on_curve, METH_VARARGS,
     "Validate a NIST P-256 affine point."},
    {"curve_p256_double_scalar", wreath_curve_p256_double_scalar, METH_VARARGS,
     "Compute a NIST P-256 double-scalar multiplication."},
    {"curve_p256_scalar", wreath_curve_p256_scalar, METH_VARARGS,
     "Multiply a NIST P-256 point by a secret scalar."},
    {"curve_p256_verify", wreath_curve_p256_verify, METH_VARARGS,
     "Verify an ECDSA P-256 equation from its SHA-256 digest."},
    {"curve_p256_sign", wreath_curve_p256_sign, METH_VARARGS,
     "Sign a SHA-256 digest with a P-256 scalar and nonce digest."},
    {"request_id_valid", wreath_request_id_valid, METH_VARARGS,
     "request_id_valid(value, max_len) -> bool"},
    {"format_server_timing", wreath_format_server_timing, METH_VARARGS,
     "format_server_timing(name, seconds) -> bytes"},
    {"prometheus_route_blocks", wreath_prometheus_route_blocks, METH_VARARGS,
     "prometheus_route_blocks(routes, names, labels=None, mapping=False) -> four sample blocks"},
    {"prometheus_global_block", wreath_prometheus_global_block, METH_VARARGS,
     "prometheus_global_block(snapshot, recorder_loss, names) -> complete global families"},
    {"prometheus_counter_block", wreath_prometheus_counter_block, METH_VARARGS,
     "prometheus_counter_block(readings, namespace) -> complete family block"},
    {"prometheus_document", wreath_prometheus_document, METH_VARARGS,
     "prometheus_document(route_blocks, global, counters, families, openmetrics) -> text"},
    {"statsd_lines", wreath_statsd_lines, METH_VARARGS,
     "statsd_lines(snapshot, recorder_loss, prefix, dogstatsd, tags, labels, previous)"},
    {"statsd_packets", wreath_statsd_packets, METH_VARARGS,
     "statsd_packets(snapshot, recorder_loss, prefix, dogstatsd, tags, labels, "
     "previous, counters, max_bytes) -> (packets, line_count)"},
    {"emf_render", wreath_emf_render, METH_VARARGS,
     "emf_render(snapshot, timestamp, recorder_loss, namespace, dims, labels, "
     "cumulative, previous, max_metrics, counters=())"},
    {"metric_delta_state", wreath_metric_delta_state, METH_NOARGS,
     "metric_delta_state() -> native per-bridge delta state"},
    {"series_reconcile", wreath_series_reconcile, METH_VARARGS,
     "series_reconcile(buckets, sparse, fills) -> dense value tuples"},
    {"series_cell_rows", wreath_series_cell_rows, METH_VARARGS,
     "series_cell_rows(rows, names, fills) -> materialized dense cells"},
    {"series_dense_rows", wreath_series_dense_rows, METH_VARARGS,
     "series_dense_rows(rows, measures, fills, grouped, periods) -> dense values"},
    {"series_spine", wreath_series_spine, METH_VARARGS,
     "series_spine(start, end, unit, zone) -> dense local-wall-clock buckets"},
    {"series_spine_length", wreath_series_spine_length, METH_VARARGS,
     "series_spine_length(start, end, unit, zone) -> dense bucket count"},
    {"series_spine_lengths", wreath_series_spine_lengths, METH_VARARGS,
     "series_spine_lengths(start, end, units, zone) -> dense bucket counts"},
    {"format_duration_parts", wreath_format_duration_parts, METH_VARARGS,
     "format_duration_parts(days, seconds, microseconds) -> ISO-8601 text"},
    {"format_iso_datetime", wreath_format_iso_datetime, METH_VARARGS,
     "format_iso_datetime(value, datetime_capi) -> ISO-8601 text"},
    {"relative_english", wreath_relative_english, METH_VARARGS,
     "relative_english(seconds, future) -> relative-time text"},
    {"relative_english_between", wreath_relative_english_between, METH_VARARGS,
     "relative_english_between(reference, moment, datetime_capi) -> relative-time text"},
    {"series_lttb", wreath_series_lttb, METH_VARARGS,
     "series_lttb(x, y, threshold) -> selected point indices"},
    {"series_path", wreath_series_path, METH_VARARGS,
     "series_path(x, y) -> gap-preserving SVG path"},
    {"series_nice_ticks", wreath_series_nice_ticks, METH_VARARGS,
     "series_nice_ticks(minimum, maximum, target) -> axis ticks"},
    {"series_chart", wreath_series_chart, METH_VARARGS,
     "series_chart(buckets, sparse, fills, downsample, full, threshold, ticks) -> compact chart"},
    {"series_chart_text", wreath_series_chart_text, METH_VARARGS,
     "Project sparse series directly to paths and final tick text."},
    {"series_chart_spine", wreath_series_chart_spine, METH_VARARGS,
     "series_chart_spine(start, end, unit, zone, sparse, fills, downsample, full, threshold, ticks) -> compact chart"},
    {"series_data", wreath_series_data, METH_VARARGS,
     "series_data(buckets, sparse, fills) -> immutable numeric series data"},
    {"series_data_chart", wreath_series_data_chart, METH_VARARGS,
     "series_data_chart(data, downsample, full, threshold, ticks) -> compact chart"},
    {"series_data_chart_text", wreath_series_data_chart_text, METH_VARARGS,
     "Project native series data with final tick text materialization."},
    {"series_data_chart_plan", wreath_series_data_chart_plan, METH_VARARGS,
     "Compile a bounded projection plan over immutable native series data."},
    {"series_chart_plan", wreath_series_chart_plan, METH_O,
     "Materialize paths and numeric axes from a compiled chart plan."},
    {"series_chart_plan_text", wreath_series_chart_plan_text, METH_O,
     "Materialize paths and final tick text from a compiled chart plan."},
    {"series_chart_plan_text_joined", wreath_series_chart_plan_text_joined,
     METH_O,
     "Write every path contiguously with final tick text from a compiled plan."},
    {"dcz_encoder_new", wreath_dcz_encoder_new, METH_O,
     "Create a dictionary-owned reusable native zstd context when libzstd is available."},
    {"dcz_compress_with", wreath_dcz_compress_with, METH_VARARGS,
     "Write a DCZ prefix and zstd payload into one final allocation."},
    {"dcz_compress_fragments_with", wreath_dcz_compress_fragments_with,
     METH_VARARGS,
     "Stream two rendered fragments into one final DCZ allocation."},
    {"build_capability_mask", wreath_build_capability_mask, METH_VARARGS,
     "build_capability_mask(capabilities, roles, permissions) -> int"},
    {"build_compiled_capability_mask", wreath_build_compiled_capability_mask,
     METH_VARARGS,
     "build_compiled_capability_mask(descriptor, roles, permissions) -> int"},
    {"normalize_authorization_decision", wreath_normalize_authorization_decision,
     METH_VARARGS,
     "normalize_authorization_decision(result, decision_type) -> decision"},
    {"cedar_is_authorized", wreath_cedar_is_authorized, METH_VARARGS,
     "cedar_is_authorized(policies, principal, action, resource, context, store)"
     " -> (allowed, reason, diagnostics)"},
    {"cedar_compile_plan", wreath_cedar_compile_plan, METH_O,
     "Compile a decision-only Cedar policy plan for route authorization."},
    {"cedar_route_denial", wreath_cedar_route_denial, METH_VARARGS,
     "Evaluate a compiled route policy plan and materialize only its denial reason."},
    {"cedar_route_denial_prepared", wreath_cedar_route_denial_prepared, METH_VARARGS,
     "Evaluate a route plan directly against a compatible request-owned context."},
    {"cedar_is_authorized_many", wreath_cedar_is_authorized_many, METH_VARARGS,
     "cedar_is_authorized_many(policies, principal, action, resources, context, store, stop)"
     " -> authorization result tuples"},
    {"cedar_is_authorized_many_native", wreath_cedar_is_authorized_many_native,
     METH_VARARGS,
     "Evaluate a Cedar batch into request-owned native decision storage."},
    {"find_header", wreath_find_header, METH_VARARGS,
     "find_header(headers, name) -> bytes | None\n"
     "Return the first value for a lowercase header name."},
    {"build_header_map", wreath_build_header_map, METH_VARARGS,
     "build_header_map(headers) -> dict[bytes, bytes]\n"
     "Build a first-value-wins mapping from an ASGI header list."},
    {"percent_decode", (PyCFunction)(void (*)(void))wreath_percent_decode,
     METH_VARARGS | METH_KEYWORDS,
     "percent_decode(data, plus_as_space=False) -> bytes"},
    {"parse_qs", wreath_parse_qs, METH_VARARGS,
     "parse_qs(query) -> list[tuple[str, str]]"},
    {"bind_query_into",
     (PyCFunction)(void (*)(void))wreath_bind_query_into, METH_FASTCALL,
     "bind_query_into(query, plan, kwargs, errors) -> errors | None\n"
     "Execute a startup-compiled exact-scalar query binding plan."},
    {"page_params", wreath_page_params, METH_VARARGS,
     "page_params(query, default_size, max_page, max_size) -> tuple"},
    {"parse_form_urlencoded", wreath_parse_form_urlencoded, METH_VARARGS,
     "parse_form_urlencoded(body, max_fields, error_type) -> (fields, all_values)"},
    {"parse_cookies", wreath_parse_cookies, METH_VARARGS,
     "parse_cookies(header) -> dict[str, str]"},
    {"parse_cookie_headers", wreath_parse_cookie_headers, METH_VARARGS,
     "Scan, bound, join and parse ASGI Cookie header fields."},
    {"sql_renumber", wreath_sql_renumber, METH_VARARGS,
     "sql_renumber(text, offset) -> str"},
    {"dkim_canonicalize_body", wreath_dkim_canonicalize_body, METH_O,
     "dkim_canonicalize_body(body) -> bytes"},
    {"recording_event_cells", wreath_recording_event_cells, METH_VARARGS,
     "recording_event_cells(payload, cell_size, version, error_type) -> tuple[bytes, ...]"},
    {"ring_file_records", wreath_ring_file_records, METH_VARARGS,
     "Recover and validate final RingRecord objects from a crash-ring image."},
    {"ring_in_flight", wreath_ring_in_flight, METH_VARARGS,
     "Return unique logged request ids without a completion cell."},
    {"ring_logs_for", wreath_ring_logs_for, METH_VARARGS,
     "Select one request's log records without decoding every cell."},
    {"scim_parse", wreath_scim_parse, METH_VARARGS,
     "scim_parse(source, attributes, types) -> filter"},
    {"scim_compile", wreath_scim_compile, METH_VARARGS,
     "scim_compile(filter, types) -> operation-owned native plan"},
    {"scim_values_at", wreath_scim_values_at, METH_VARARGS,
     "scim_values_at(resource, path, types) -> list"},
    {"scim_matches", wreath_scim_matches, METH_VARARGS,
     "scim_matches(filter, resource, types) -> bool"},
    {"scim_filter", wreath_scim_filter, METH_VARARGS,
     "scim_filter(filter, resources, types, invert) -> list"},
    {"ws_mask", wreath_ws_mask, METH_VARARGS,
     "ws_mask(data, key) -> bytes\nXOR-(un)mask a WebSocket payload."},
    {"b64encode", (PyCFunction)(void (*)(void))wreath_b64encode,
     METH_VARARGS | METH_KEYWORDS,
     "b64encode(data, urlsafe=False, pad=True) -> str"},
    {"simd_arms", wreath_simd_arms, METH_NOARGS,
     "simd_arms() -> tuple[str, ...]\nScanner arms this build can reach."},
    {"simd_probe", wreath_simd_probe, METH_VARARGS,
     "simd_probe(kind, arm, data, key=None)\nRun one scanner arm by name."},
    {"ws_parse_frame", wreath_ws_parse_frame, METH_VARARGS,
     "ws_parse_frame(buffer, offset=0) -> (fin, opcode, payload, consumed) | None"},
    {"ws_build_frame", (PyCFunction)(void (*)(void))wreath_ws_build_frame,
     METH_VARARGS | METH_KEYWORDS,
     "ws_build_frame(opcode, payload, fin=True, mask_key=None) -> bytes"},
    {"multipart_parse", (PyCFunction)(void (*)(void))wreath_multipart_parse,
     METH_VARARGS | METH_KEYWORDS,
     "multipart_parse(body, boundary, max_parts=-1, max_part_header_bytes=-1, "
     "max_part_bytes=-1) -> list[(headers, data)]\nA negative limit means no limit."},
    {"multipart_part_info", wreath_multipart_part_info, METH_O,
     "multipart_part_info(header_block) -> (headers, name, filename)"},
    {"json_dumps", wreath_json_dumps, METH_O,
     "json_dumps(obj) -> bytes\nSerialize to compact UTF-8 JSON."},
    {"graphql_project_json", wreath_graphql_project_json, METH_VARARGS,
     "Compile a plain GraphQL projection for direct JSON output."},
    {"msgpack_dumps", wreath_msgpack_dumps, METH_O,
     "msgpack_dumps(obj) -> bytes\nSerialize to MessagePack."},
    {"aesgcm_arms", wreath_aesgcm_arms, METH_NOARGS,
     "aesgcm_arms() -> tuple[str, ...]\n"
     "('aesni', 'pclmul') when this CPU and build can run the hardware "
     "AES-128-GCM path, or () when wreath._webpush must use its Python arm.\n"
     "build sentinel: wreath-aesgcm-aesni-pclmul"},
    {"aes128gcm_encrypt", wreath_aes128gcm_encrypt, METH_VARARGS,
     "aes128gcm_encrypt(key, nonce, plaintext, aad) -> ciphertext || tag"},
    {"aes128gcm_decrypt", wreath_aes128gcm_decrypt, METH_VARARGS,
     "aes128gcm_decrypt(key, nonce, message, aad) -> plaintext, or None when "
     "the tag does not verify."},
    {"_aes128gcm_encrypt_scalar", wreath_aes128gcm_encrypt_scalar, METH_VARARGS,
     "Internal scalar-C AES-128-GCM encryption test entry."},
    {"_aes128gcm_decrypt_scalar", wreath_aes128gcm_decrypt_scalar, METH_VARARGS,
     "Internal scalar-C AES-128-GCM decryption test entry."},
    {"geo_haversine", (PyCFunction)(void (*)(void))wreath_geo_haversine,
     METH_FASTCALL,
     "geo_haversine(lat1, lon1, lat2, lon2) -> float\n"
     "Great-circle metres on the IUGG mean-radius sphere."},
    {"geo_trajectory_grid_summary", wreath_geo_trajectory_grid_summary,
     METH_VARARGS,
     "geo_trajectory_grid_summary(fixes, start, end, extent, steps, shape) -> cells, speed"},
    {"geo_trajectory_compile", wreath_geo_trajectory_compile, METH_VARARGS,
     "geo_trajectory_compile(fixes, error_type, coordinate_type, datetime_capi) -> native trajectory"},
    {"geo_trajectory_fixes", wreath_geo_trajectory_fixes, METH_O,
     "geo_trajectory_fixes(trajectory) -> timestamp/latitude/longitude rows"},
    {"geo_trajectory_info", wreath_geo_trajectory_info, METH_O,
     "geo_trajectory_info(trajectory) -> count, distance, duration, speed"},
    {"geo_trajectory_between", wreath_geo_trajectory_between, METH_VARARGS,
     "geo_trajectory_between(trajectory, start, end) -> native trajectory"},
    {"protobuf_compile", wreath_protobuf_compile, METH_VARARGS,
     "Compile protobuf declaration metadata into an operation descriptor."},
    {"protobuf_encode", wreath_protobuf_encode, METH_VARARGS,
     "protobuf_encode(plan, values, unknown=b'') -> bytes\n"
     "Encode values in plan order to protobuf wire bytes."},
    {"protobuf_decode", wreath_protobuf_decode, METH_VARARGS,
     "protobuf_decode(plan, data) -> (values, unknown)\n"
     "Decode protobuf wire bytes against a compiled plan."},
    {"protobuf_encode_message", wreath_protobuf_encode_message, METH_O,
     "protobuf_encode_message(message) -> bytes"},
    {"protobuf_decode_message", wreath_protobuf_decode_message, METH_VARARGS,
     "protobuf_decode_message(cls, data) -> message"},
    {"protobuf_otlp_from_json", wreath_protobuf_otlp_from_json, METH_VARARGS,
     "Build a declared OTLP message from its JSON-shaped mapping."},
    {"protobuf_encode_otlp_json", wreath_protobuf_encode_otlp_json, METH_VARARGS,
     "Encode an OTLP JSON-shaped mapping directly to protobuf bytes."},
    {"protobuf_encode_otlp_metrics", wreath_protobuf_encode_otlp_metrics, METH_VARARGS,
     "Encode an OTLP metric snapshot directly to protobuf bytes."},
    {"protobuf_encode_otlp_traces", wreath_protobuf_encode_otlp_traces, METH_VARARGS,
     "Encode projected traces directly to OTLP protobuf bytes."},
    {"protobuf_encode_otlp_logs", wreath_protobuf_encode_otlp_logs, METH_VARARGS,
     "Encode projected logs directly to OTLP protobuf bytes."},
    {"xml_configure", wreath_xml_configure, METH_O,
     "xml_configure(refusal_type) -> None"},
    {"xml_parse", wreath_xml_parse, METH_VARARGS,
     "xml_parse(data, element_type, max_bytes, max_depth, max_elements, max_attributes, "
     "max_attribute_bytes) -> node\nStrict XML, with a byte span per element."},
    {"xml_c14n", wreath_xml_c14n, METH_VARARGS,
     "xml_c14n(data, start, end, inherited, inclusive, *limits) -> bytes\n"
     "Exclusive XML Canonicalization 1.0 of one subtree's source bytes."},
    {"sse_frame", wreath_sse_frame, METH_VARARGS,
     "sse_frame(comment, name, ident, retry, data) -> bytes\nFrame one SSE event."},
    {"json_configure", wreath_json_configure, METH_VARARGS,
     "json_configure(temporal_types, format_iso) -> None"},
    {"json_loads", wreath_json_loads, METH_O,
     "json_loads(data) -> object\n"
     "Parse JSON from str/bytes/bytearray with stdlib json.loads semantics."},
    {"jsonpath_find", wreath_jsonpath_find, METH_VARARGS,
     "jsonpath_find(program, value, max_visits, error_type, fullmatch, search, "
     "pattern_error) -> nodes\nExecute a compiled RFC 9535 query."},
    {"template_compile", wreath_template_compile, METH_O,
     "template_compile(tape) -> program\n"
     "Decode a template tape once for repeated rendering."},
    {"template_render_compiled", wreath_template_render_compiled, METH_VARARGS,
     "template_render_compiled(program, context, max_output) -> bytes\n"
     "Execute a decoded template program to escaped UTF-8."},
    {"template_render_compiled_tail", wreath_template_render_compiled_tail,
     METH_VARARGS,
     "Render a decoded template and append one immutable byte tail."},
    {"template_configure", wreath_template_configure, METH_VARARGS,
     "template_configure(markup_type, render_error_type) -> None"},
    {"template_record_configure", wreath_template_record_configure, METH_O,
     "template_record_configure(record_c_api) -> None"},
    {"html_response_configure", wreath_html_response_configure, METH_VARARGS,
     "Install the exact HTMLResponse constructor fast path."},
    {"http_response_framing", wreath_http_response_framing, METH_VARARGS,
     "http_response_framing(method, status, headers) -> (mode, length)"},
    {"http_response_keeps_alive", wreath_http_response_keeps_alive, METH_VARARGS,
     "http_response_keeps_alive(minor, headers, framed) -> bool"},
    {"http_serialize_request", wreath_http_serialize_request, METH_VARARGS,
     "http_serialize_request(method, target, host, headers, body) -> bytes"},
    {"select_content_encoding", wreath_select_content_encoding, METH_O,
     "select_content_encoding(accept_encoding) -> str | None"},
    {"select_prepared_content_encoding", wreath_select_prepared_content_encoding,
     METH_VARARGS,
     "select_prepared_content_encoding(accept_encoding, dcz_available) -> str | None"},
    {"is_compressible_content_type", wreath_is_compressible_content_type, METH_O,
     "is_compressible_content_type(content_type) -> bool"},
    {"cache_control_flags", wreath_cache_control_flags, METH_O,
     "cache_control_flags(value) -> int"},
    {"origin_matches", wreath_origin_matches, METH_VARARGS,
     "origin_matches(origin, allowed) -> bool"},
    {"append_missing_headers", wreath_append_missing_headers, METH_VARARGS,
     "append_missing_headers(headers, additions) -> None"},
    {"validate_response_headers", wreath_validate_response_headers, METH_O,
     "validate_response_headers(headers) -> (has_content_type, content_length)"},
    {"append_vary", wreath_append_vary, METH_VARARGS,
     "append_vary(headers, token) -> None"},
    {"replace_content_length", wreath_replace_content_length, METH_VARARGS,
     "replace_content_length(headers, length) -> None"},
    {"replace_response_header", wreath_replace_response_header, METH_VARARGS,
     "replace_response_header(headers, name, value) -> None"},
    {"replace_cookie", wreath_replace_cookie, METH_VARARGS,
     "replace_cookie(headers, prefix, value) -> None"},
    {"replace_server_timing", wreath_replace_server_timing, METH_VARARGS,
     "replace_server_timing(headers, metric, value) -> None"},
    {"find_response_header", wreath_find_response_header, METH_VARARGS,
     "find_response_header(headers, name) -> bytes | None"},
    {NULL, NULL, 0, NULL},
};

static struct PyModuleDef core_module = {
    PyModuleDef_HEAD_INIT,
    "wreath._native._core",
    "The C core Wreath requires: routing, HTTP, codecs, headers, validation, Cedar.",
    -1,
    core_methods,
    NULL,
    NULL,
    NULL,
    NULL,
};

static WreathCoreCAPI core_capi = {
    wreath_ws_parse_header_raw,
    wreath_ws_unmask_raw,
    wreath_parse_cookie_data_raw,
    wreath_user_agent_blocked,
    wreath_user_agent_database_check,
    wreath_gzip_compress_workspace,
    wreath_gzip_fragment_compress_workspace,
    wreath_gzip_format_object,
    wreath_replace_cookie_inplace,
    wreath_replace_server_timing_inplace,
};


PyMODINIT_FUNC
PyInit__core(void)
{
    PyObject *module = PyModule_Create(&core_module);
    PyObject *capsule;
    if (module == NULL) {
        return NULL;
    }
    if (wreath_http_register_request_parser(module) < 0 ||
        wreath_http_register_response_parser(module) < 0 ||
        wreath_security_ready() < 0 || wreath_jose_ready() < 0 ||
        wreath_observability_ready() < 0 || wreath_protobuf_ready() < 0 ||
        wreath_graphql_parser_ready() < 0 || wreath_graphql_ready() < 0 ||
        wreath_scim_ready() < 0 || wreath_http_replay_ready() < 0 ||
        wreath_series_ready() < 0 ||
        wreath_register_policy_router(module) < 0 ||
        wreath_register_webpolicy(module) < 0 || wreath_register_proxy(module) < 0 ||
        wreath_register_ratelimit(module) < 0 ||
        wreath_register_scheduler(module) < 0 ||
        wreath_register_kv(module) < 0 || wreath_register_queue(module) < 0 ||
        wreath_register_grpc(module) < 0 || wreath_register_multipart(module) < 0 ||
        wreath_register_flight_project(module) < 0 ||
        wreath_register_client_facts(module) < 0 ||
        wreath_register_zip_builder(module) < 0 ||
        wreath_register_data_kernels(module) < 0) {
        Py_DECREF(module);
        return NULL;
    }
    /* C-level API for sibling extensions (the native server) so hot paths
     * can share this module's parsers without per-call Python overhead. */
    capsule = PyCapsule_New(&core_capi, WREATH_CORE_CAPI_NAME, NULL);
    if (capsule == NULL || PyModule_AddObject(module, "_C_API", capsule) < 0) {
        Py_XDECREF(capsule);
        Py_DECREF(module);
        return NULL;
    }
    return module;
}
