create table "tracking"."animals" ();
create table "tracking"."fixes" ();
create table "tracking"."landmarks" ();
create table "tracking"."collars" ();
alter table "tracking"."landmarks" add column "longitude" double precision not null;
alter table "tracking"."fixes" add column "relay" text not null;
alter table "tracking"."animals" add column "name" text not null;
alter table "tracking"."collars" add column "id" bigint not null;
alter table "tracking"."fixes" add column "received_at" timestamp with time zone not null;
alter table "tracking"."fixes" add column "accuracy_m" double precision;
alter table "tracking"."collars" add column "animal_id" bigint not null;
alter table "tracking"."animals" add column "taxon" text not null;
alter table "tracking"."animals" add column "protection" text not null;
alter table "tracking"."fixes" add column "battery_pct" smallint not null;
alter table "tracking"."landmarks" add column "name" text not null;
alter table "tracking"."landmarks" add column "id" bigint not null;
alter table "tracking"."fixes" add column "animal_id" bigint not null;
alter table "tracking"."fixes" add column "leg_m" double precision;
alter table "tracking"."fixes" add column "collar_id" bigint not null;
alter table "tracking"."collars" add column "fitted_at" timestamp with time zone not null;
alter table "tracking"."fixes" add column "recorded_at" timestamp with time zone not null;
alter table "tracking"."fixes" add column "longitude" double precision not null;
alter table "tracking"."collars" add column "removed_at" timestamp with time zone;
alter table "tracking"."landmarks" add column "latitude" double precision not null;
alter table "tracking"."landmarks" add column "kind" text not null;
alter table "tracking"."fixes" add column "latitude" double precision not null;
alter table "tracking"."animals" add column "id" bigint not null;
alter table "tracking"."collars" add column "serial" text not null;
alter table "tracking"."fixes" add column "satellites" integer not null;
alter table "tracking"."landmarks" add constraint "wreath_288435ba44150dc5" primary key ("id");
alter table "tracking"."collars" add constraint "wreath_6398fd495c2c8b68" unique ("serial");
alter table "tracking"."landmarks" add constraint "wreath_8481f93ec972bcba" unique ("name");
alter table "tracking"."animals" add constraint "wreath_8dcbbd67c314a0f2" unique ("name");
alter table "tracking"."collars" add constraint "wreath_a68b28971882fe38" primary key ("id");
alter table "tracking"."fixes" add constraint "wreath_c567d503613830d3" primary key ("collar_id", "recorded_at");
alter table "tracking"."animals" add constraint "wreath_e15f08aa06a34e2d" primary key ("id");
create index "wreath_053325473b31456d" on "tracking"."fixes" ("animal_id", "received_at");
create index "wreath_290662c864b6d860" on "tracking"."collars" ("animal_id", "fitted_at") where (removed_at IS NULL);
create index "wreath_5637df8dc01a1017" on "tracking"."fixes" ("latitude", "longitude");
create index "wreath_a007ea693e49c646" on "tracking"."fixes" ("animal_id", "recorded_at");
create index "wreath_a86e78d97d50ee74" on "tracking"."animals" ("protection", "id") where (protection = ANY (ARRAY['sensitive'::text, 'restricted'::text]));
create index "wreath_f4fb75ef89a81e01" on "tracking"."collars" ("animal_id");
alter table "tracking"."fixes" add constraint "wreath_1db3c410709b2033" foreign key ("animal_id") references "tracking"."animals" ("id");
alter table "tracking"."collars" add constraint "wreath_31b949702c3de154" foreign key ("animal_id") references "tracking"."animals" ("id");
alter table "tracking"."fixes" add constraint "wreath_b2068b28a17717f9" foreign key ("collar_id") references "tracking"."collars" ("id");
