"""The public surface: emit one module, or port a whole tree.

Every emitted file is re-`ast.parse`d as a round-trip guard, and carries a
provenance header so a re-run can tell its own output from a hand edit."""

from __future__ import annotations

import ast
import hashlib
from dataclasses import dataclass, field
from pathlib import Path

from ..analyzer import (
    _SKIPPABLE,
    TreeContext,
    _Imports,
    _iter_py,
    _relative_to,
    _skip_detail,
    _skip_reason,
    module_findings,
    module_pk_types,
)
from ..ir import SkippedFile
from .emitter import _Emitter
from .targets import _HEADER_PREFIX


class EmitError(Exception):
    """A generated file failed the round-trip ast.parse guard (a tool bug)."""


@dataclass(frozen=True)
class PortResult:
    """What one `port_tree` run wrote, left alone, and could not read.

    `skipped` and `failed` are deliberately separate. A *skip* is a success:
    the output was already current, or it had been hand-edited and refusing to
    clobber it is the correct answer. A *failure* is a file that could not be
    read or translated at all, so nothing about it reached the output tree. A
    caller that folded the two together could not tell "your tree is already
    ported" from "a third of your tree never made it".
    """

    written_files: list[Path] = field(default_factory=list)
    regenerated: list[Path] = field(default_factory=list)
    skipped: list[Path] = field(default_factory=list)
    failed: list[SkippedFile] = field(default_factory=list)


# --------------------------------------------------------------------------- public
def _provenance(source: str, body: str) -> str:
    src_h = hashlib.sha256(source.encode("utf-8")).hexdigest()
    out_h = hashlib.sha256(body.encode("utf-8")).hexdigest()
    return (
        f"{_HEADER_PREFIX} generated by `wreath port` — review before use.\n"
        f"{_HEADER_PREFIX} source-sha256={src_h}\n"
        f"{_HEADER_PREFIX} output-sha256={out_h}\n"
    )


def _read_source(source) -> str:
    """A `Path` is read from disk; a `str` is treated as source text verbatim."""
    if isinstance(source, Path):
        return source.read_text(encoding="utf-8")
    return source


def emit_module(source, context: TreeContext | None = None, *, opinionated: bool = False) -> str:
    """Port one module. `source` may be a Path/path-string (read) or source text.

    Returns the ported source (with a provenance header), preserving every function
    body verbatim. Raises `EmitError` if the result is not valid Python.

    `context` carries what the rest of the tree knows — which models exist, what
    type each primary key is, which columns each one declares — so a foreign key
    onto a model in another file gets the right type and a body parameter is
    recognized as a body. `port_tree` reads it once for the whole tree; a lone
    module falls back to what it can see in itself.

    Two orderings here are load-bearing:

    * the walk runs **before** the imports are rewritten, because whether a name
      can be dropped from an import depends on whether every use of it was
      replaced, and only the walk knows that;
    * the emitter's own notes are written **before** the analyzer's, so where
      both have something to say about a line, the more specific one wins.
    """
    text = _read_source(source)
    tree = ast.parse(text)
    imports = _Imports().visit(tree)
    if context is None:
        context = (
            TreeContext.of([source], opinionated=opinionated)
            if isinstance(source, Path)
            else TreeContext()
        )
    resolved = {**context.pk_types, **module_pk_types(tree, imports)}
    emitter = _Emitter(text, imports, resolved, opinionated=opinionated)
    emitter.orm_columns = context.orm_columns
    emitter.orm_relations = context.orm_relations
    emitter.orm_tables = context.orm_tables
    emitter.orm_unique_constraints = context.orm_unique_constraints
    emitter.orm_mixins = frozenset(context.index.get("orm_mixin", ()))
    emitter.django = context.django
    emitter.pydantic_models = frozenset(context.index.get("pydantic", ()))
    emitter.settings_models = frozenset(context.index.get("settings", ()))
    emitter.session_functions = context.session_functions
    emitter.session_definition_sites = context.session_definition_sites
    emitter.session_call_sites = context.session_call_sites
    emitter.session_sites_resolved = context.session_sites_resolved
    if isinstance(source, Path):
        emitter._source_path = str(source.resolve())
    emitter.collect_dep_targets(tree)
    emitter.visit(tree)
    path = source if isinstance(source, Path) else Path("<module>")
    emitter.annotate_findings(module_findings(path, path, tree, imports, context))
    emitter.rewrite_imports(tree)
    emitter.inject_imports()
    body = emitter.buf.render()
    try:
        ast.parse(body)
    except SyntaxError as exc:  # pragma: no cover - tool-bug guard
        raise EmitError(f"emitted module is not valid Python: {exc}") from exc
    return _provenance(text, body) + body


def _strip_provenance(text: str) -> str:
    lines = text.splitlines(keepends=True)
    i = 0
    while i < len(lines) and lines[i].startswith(_HEADER_PREFIX):
        i += 1
    return "".join(lines[i:])


def _output_hash(text: str) -> str:
    return hashlib.sha256(_strip_provenance(text).encode("utf-8")).hexdigest()


def _recorded_hashes(text: str) -> tuple[str | None, str | None]:
    src = out = None
    for line in text.splitlines():
        if not line.startswith(_HEADER_PREFIX):
            break
        if "source-sha256=" in line:
            src = line.split("source-sha256=", 1)[1].strip()
        elif "output-sha256=" in line:
            out = line.split("output-sha256=", 1)[1].strip()
    return src, out


def port_tree(
    root: str | Path,
    output: str | Path | None = None,
    *,
    in_place: bool = False,
    force: bool = False,
    opinionated: bool = False,
) -> PortResult:
    """Port every `.py` under `root` into a sister tree (or in place).

    Idempotent: an unchanged source whose output still carries a matching provenance
    hash is skipped; an output that was hand-edited (its body hash no longer matches
    the recorded `output-sha256`) is left untouched unless `force`.

    **A source that cannot be read is recorded in `failed`, not fatal** — the same
    rule `analyze` follows, for the same reason: one broken symlink in a large tree
    must not end the run. **A destination that cannot be written *is* fatal**, because
    it condemns every remaining file and a partial output tree is indistinguishable
    from a complete one.
    """
    root = Path(root)
    if in_place and not force:
        raise ValueError("wreath port --in-place requires --force (or use --output <dir>)")
    if in_place:
        out_root = root
    elif output is None:
        raise ValueError("wreath port needs --output <dir> (or --in-place --force)")
    else:
        out_root = Path(output)
    result = PortResult()
    # One pass over the tree first, so a foreign key onto a model declared in
    # another file gets that model's real key type instead of a guess.
    sources = list(_iter_py(root))
    context = TreeContext.of(sources, opinionated=opinionated)
    for src_path in sources:
        rel = src_path.relative_to(root) if root != src_path else src_path.name
        dest = (out_root / rel) if not in_place else src_path

        # Reads are per-file recoverable; writes are not. Everything inside this
        # block touches only *input* — the source, and any existing output whose
        # provenance decides what to do next — so one bad file takes itself out
        # of the run and leaves the rest in, exactly as `analyze` does. The
        # writes below sit outside it deliberately (see the comment there).
        try:
            source = src_path.read_text(encoding="utf-8")
            if dest.exists() and not in_place:
                existing = dest.read_text(encoding="utf-8")
                rec_src, rec_out = _recorded_hashes(existing)
                cur_src = hashlib.sha256(source.encode("utf-8")).hexdigest()
                if rec_out is not None and rec_out != _output_hash(existing) and not force:
                    result.skipped.append(dest)  # hand-edited output — refuse to clobber
                    continue
                if rec_src == cur_src:
                    result.skipped.append(dest)  # unchanged source — idempotent no-op
                    continue
                emitted = emit_module(src_path, context, opinionated=opinionated)
                regenerating = True
            else:
                emitted = emit_module(src_path, context, opinionated=opinionated)
                regenerating = False
        except _SKIPPABLE as exc:
            # An unreadable source, a non-UTF-8 one, or one that is not valid
            # Python: recorded and stepped over. `EmitError` is deliberately not
            # caught — a structurally broken *emit* is a tool bug, and turning it
            # into a per-file skip is how a codemod quietly drops your code.
            key = _relative_to(src_path, root)
            result.failed.append(SkippedFile(key, _skip_reason(exc), _skip_detail(exc)))
            continue

        # A destination that cannot be written is fatal, and stays uncaught. An
        # unreadable *source* costs one file; an unwritable *destination* means
        # the output tree is wrong — a full disk, a read-only mount, a bad
        # --output path — and every remaining file would hit it too. Continuing
        # would hand back a half-written tree that looks like a complete port.
        if regenerating:
            dest.write_text(emitted, encoding="utf-8")
            result.regenerated.append(dest)
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(emitted, encoding="utf-8")
            result.written_files.append(dest)
    return result
