// Generated by wreath typegen. Do not edit.
// This file is owned by wreath-typegen.json; edits are overwritten.

import type {
  DeleteItemsByItemIdParameters,
  GetInventoryBySkuParameters,
  GetItemParameters,
  GetItemsParameters,
  Item,
  ItemPage,
  Item_tests_typegen_other,
  Tag,
} from "./models";

export interface WreathClientOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  headers?: HeadersInit | (() => HeadersInit | Promise<HeadersInit>);
}

export class WreathApiError extends Error {
  readonly status: number;
  readonly statusText: string;
  readonly headers: Headers;
  readonly body: unknown;

  constructor(status: number, statusText: string, headers: Headers, body: unknown) {
    super(`Wreath API error ${status} ${statusText}`);
    this.name = "WreathApiError";
    this.status = status;
    this.statusText = statusText;
    this.headers = headers;
    this.body = body;
  }
}

async function resolveHeaders(
  source: WreathClientOptions["headers"],
): Promise<HeadersInit | undefined> {
  return typeof source === "function" ? await source() : source;
}

async function decodeBody(response: Response): Promise<unknown> {
  const contentType = response.headers.get("content-type") ?? "";
  if (contentType.includes("application/json")) {
    return await response.json();
  }
  return await response.text();
}

export class WreathClient {
  private readonly baseUrl: string;
  private readonly fetchImpl: typeof globalThis.fetch;
  private readonly headers: WreathClientOptions["headers"];

  constructor(options: WreathClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/$/, "");
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    this.headers = options.headers;
  }

    async createItem(body: Item, init?: RequestInit): Promise<Item> {
      const url = new URL(`${this.baseUrl}/items`);
      const headers = new Headers(await resolveHeaders(this.headers));
      headers.set("content-type", "application/json");
      const response = await this.fetchImpl(url, { method: "POST", body: JSON.stringify(body), headers, ...init });
      if (!response.ok) {
        throw new WreathApiError(
          response.status,
          response.statusText,
          response.headers,
          await decodeBody(response).catch(() => undefined),
        );
      }
      return (await decodeBody(response)) as Item;
    }

    async deleteItemsByItemId(parameters: DeleteItemsByItemIdParameters, init?: RequestInit): Promise<null> {
      const url = new URL(`${this.baseUrl}/items/${encodeURIComponent(String(parameters.itemId))}`);
      const headers = new Headers(await resolveHeaders(this.headers));
      const response = await this.fetchImpl(url, { method: "DELETE", headers, ...init });
      if (!response.ok) {
        throw new WreathApiError(
          response.status,
          response.statusText,
          response.headers,
          await decodeBody(response).catch(() => undefined),
        );
      }
      return (await decodeBody(response)) as null;
    }

    async getInventoryBySku(parameters: GetInventoryBySkuParameters, init?: RequestInit): Promise<Item_tests_typegen_other> {
      const url = new URL(`${this.baseUrl}/inventory/${encodeURIComponent(String(parameters.sku))}`);
      const headers = new Headers(await resolveHeaders(this.headers));
      const response = await this.fetchImpl(url, { method: "GET", headers, ...init });
      if (!response.ok) {
        throw new WreathApiError(
          response.status,
          response.statusText,
          response.headers,
          await decodeBody(response).catch(() => undefined),
        );
      }
      return (await decodeBody(response)) as Item_tests_typegen_other;
    }

    async getItem(parameters: GetItemParameters, init?: RequestInit): Promise<Item> {
      const url = new URL(`${this.baseUrl}/items/${encodeURIComponent(String(parameters.itemId))}`);
      if (parameters.expand !== undefined) url.searchParams.set("expand", String(parameters.expand));
      if (parameters.traceId !== undefined) url.searchParams.set("trace_id", String(parameters.traceId));
      const headers = new Headers(await resolveHeaders(this.headers));
      const response = await this.fetchImpl(url, { method: "GET", headers, ...init });
      if (!response.ok) {
        throw new WreathApiError(
          response.status,
          response.statusText,
          response.headers,
          await decodeBody(response).catch(() => undefined),
        );
      }
      return (await decodeBody(response)) as Item;
    }

    async getItems(parameters: GetItemsParameters, init?: RequestInit): Promise<ItemPage> {
      const url = new URL(`${this.baseUrl}/items`);
      if (parameters.limit !== undefined) url.searchParams.set("limit", String(parameters.limit));
      if (parameters.cursor !== undefined) url.searchParams.set("cursor", String(parameters.cursor));
      const headers = new Headers(await resolveHeaders(this.headers));
      const response = await this.fetchImpl(url, { method: "GET", headers, ...init });
      if (!response.ok) {
        throw new WreathApiError(
          response.status,
          response.statusText,
          response.headers,
          await decodeBody(response).catch(() => undefined),
        );
      }
      return (await decodeBody(response)) as ItemPage;
    }
}

export function createWreathClient(options: WreathClientOptions): WreathClient {
  return new WreathClient(options);
}
