// Generated by wreath typegen. Do not edit.
// This file is owned by wreath-typegen.json; edits are overwritten.

export * from "./models";
export * from "./client";
export * from "./react-query";

export const defaultBaseUrl: string =
  (import.meta as unknown as { env?: Record<string, string> }).env?.VITE_API_URL ?? "";
