// Generated by wreath typegen. Do not edit.
// This file is owned by wreath-typegen.json; edits are overwritten.
export interface Item {
  name: string;
  price: number;
  priority: "low" | "high";
  kind: "basic" | "premium";
  tags?: Tag[];
  coordinates?: [number, number] | null;
  metadata?: Record<string, string>;
  parent?: Item | null;
}

export interface ItemPage {
  items: Item[];
  total: number;
}

export interface Item_tests_typegen_other {
  sku: string;
  quantity: number;
}

export interface Tag {
  name: string;
  color?: string | null;
}

export interface DeleteItemsByItemIdParameters {
  itemId: number;
}

export interface GetInventoryBySkuParameters {
  sku: string;
}

export interface GetItemParameters {
  itemId: number;
  expand?: boolean;
  traceId?: string;
}

export interface GetItemsParameters {
  limit?: number;
  cursor?: string | null;
}
