// Generated by wreath typegen. Do not edit.
// This file is owned by wreath-typegen.json; edits are overwritten.

import { createContext, useContext } from "react";
import {
  useQuery,
  useMutation,
  type UseQueryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";
import { WreathClient, WreathApiError } from "./client";
import type {
  DeleteItemsByItemIdParameters,
  GetInventoryBySkuParameters,
  GetItemParameters,
  GetItemsParameters,
  Item,
  ItemPage,
  Item_tests_typegen_other,
  Tag,
} from "./models";

const WreathClientContext = createContext<WreathClient | null>(null);
export const WreathClientProvider = WreathClientContext.Provider;

export function useWreathClient(): WreathClient {
  const client = useContext(WreathClientContext);
  if (client === null) {
    throw new Error("WreathClientProvider is missing from the tree");
  }
  return client;
}

export function useCreateItem(options?: Omit<UseMutationOptions<Item, WreathApiError, Item>, "mutationFn">) {
  const client = useWreathClient();
  return useMutation({
    ...options,
    mutationFn: (variables: Item) => client.createItem(variables),
  });
}

export function useDeleteItemsByItemId(parameters: DeleteItemsByItemIdParameters, options?: Omit<UseMutationOptions<null, WreathApiError, void>, "mutationFn">) {
  const client = useWreathClient();
  return useMutation({
    ...options,
    mutationFn: (_variables: void) => client.deleteItemsByItemId(parameters),
  });
}

export function useGetInventoryBySku(parameters: GetInventoryBySkuParameters, options?: Omit<UseQueryOptions<Item_tests_typegen_other, WreathApiError>, "queryKey" | "queryFn">) {
  const client = useWreathClient();
  return useQuery({
    ...options,
    queryKey: ["getInventoryBySku", parameters] as const,
    queryFn: () => client.getInventoryBySku(parameters),
  });
}

export function useGetItem(parameters: GetItemParameters, options?: Omit<UseQueryOptions<Item, WreathApiError>, "queryKey" | "queryFn">) {
  const client = useWreathClient();
  return useQuery({
    ...options,
    queryKey: ["getItem", parameters] as const,
    queryFn: () => client.getItem(parameters),
  });
}

export function useGetItems(parameters: GetItemsParameters, options?: Omit<UseQueryOptions<ItemPage, WreathApiError>, "queryKey" | "queryFn">) {
  const client = useWreathClient();
  return useQuery({
    ...options,
    queryKey: ["getItems", parameters] as const,
    queryFn: () => client.getItems(parameters),
  });
}
