"""Thin presentation-only bindings for Wreath-metal migration commands."""

from __future__ import annotations

import argparse
import asyncio
import json
import shutil
import struct
import tempfile
from collections.abc import Callable
from pathlib import Path
from typing import Any

from .migrations import (
    _build_native_artifact,
    _load_native_artifact,
    _verify_native_chain,
    detect_single,
    generate_single_plan,
)


async def _detect(namespace: argparse.Namespace, application: Any) -> dict[str, Any]:
    registries = getattr(application, "_orm_registries", {})
    registry = registries.get(namespace.database)
    if registry is None:
        known = ", ".join(sorted(registries)) or "none"
        raise ValueError(
            f"application has no ORM registry {namespace.database!r}; configured: {known}"
        )
    database = registry.database
    await database.start()
    workload = "read"
    try:
        try:
            database.pool(workload)
        except KeyError:
            workload = "write"
        connection = await database.acquire(workload)
        try:
            detection = await detect_single(registry, connection)
        finally:
            await database.release(workload, connection)
    finally:
        await database.stop()
    return {
        "current": detection.current,
        "operation_count": detection.diff.operation_count,
        "desired_fingerprint": detection.desired_fingerprint.hex(),
        "actual_fingerprint": detection.actual_fingerprint.hex(),
    }


def _unpack_named_plan(tape: bytes) -> list[dict[str, Any]]:
    if len(tape) < 12 or tape[:4] != b"WMP1":
        raise ValueError("native named migration plan is invalid")
    count = int.from_bytes(tape[8:12], "little")
    offset = 12
    operations: list[dict[str, Any]] = []
    action_names = {1: "add", 2: "drop", 3: "alter"}
    kind_names = {1: "table", 2: "column", 3: "constraint", 4: "index"}
    for _ in range(count):
        if len(tape) - offset < 20:
            raise ValueError("native named migration plan is truncated")
        action, kind, *lengths = struct.unpack_from("<IIHHHHHH", tape, offset)
        offset += 20
        if lengths[5] != 0:
            raise ValueError("native named migration plan has unsupported flags")
        values: list[str] = []
        for length in lengths[:5]:
            if length > len(tape) - offset:
                raise ValueError("native named migration plan is truncated")
            values.append(tape[offset : offset + length].decode("utf-8"))
            offset += length
        operations.append(
            {
                "action": action_names.get(action, f"unknown-{action}"),
                "kind": kind_names.get(kind, f"unknown-{kind}"),
                "schema": values[0],
                "table": values[1],
                "name": values[2],
                "before": values[3],
                "after": values[4],
            }
        )
    if offset != len(tape):
        raise ValueError("native named migration plan has trailing bytes")
    return operations


def _quote_identifier(value: str) -> str:
    if not value or "\x00" in value:
        raise ValueError("migration identifier is empty or contains NUL")
    return '"' + value.replace('"', '""') + '"'


def _render_column(signature: str) -> str | None:
    parts = signature.split("\x1f")
    if len(parts) != 7 or parts[0] != "column" or parts[5]:
        return None
    types = {
        "16": "boolean",
        "17": "bytea",
        "20": "bigint",
        "23": "integer",
        "25": "text",
        "701": "double precision",
        "1082": "date",
        "1184": "timestamp with time zone",
        "1700": "numeric",
        "2950": "uuid",
        "3802": "jsonb",
    }
    sql_type = types.get(parts[1])
    if sql_type is None:
        return None
    clauses = [sql_type]
    if parts[4] == "a":
        clauses.append("generated always as identity")
    elif parts[4] == "d":
        clauses.append("generated by default as identity")
    if parts[6]:
        clauses.append(f"default {parts[6]}")
    if parts[3] == "1":
        clauses.append("not null")
    return " ".join(clauses)


def _render_review_sql(operations: list[dict[str, Any]]) -> str:
    """Render deterministic review SQL; this output is never execution input."""
    rank = {
        ("drop", "constraint"): 0,
        ("drop", "column"): 1,
        ("drop", "table"): 2,
        ("add", "table"): 3,
        ("add", "column"): 4,
        ("alter", "column"): 5,
        ("add", "constraint"): 6,
    }
    ordered = sorted(
        enumerate(operations),
        key=lambda item: (rank.get((item[1]["action"], item[1]["kind"]), 99), item[0]),
    )
    statements: list[str] = []
    for _, operation in ordered:
        action = operation["action"]
        kind = operation["kind"]
        schema = _quote_identifier(operation["schema"])
        table = _quote_identifier(operation["table"])
        qualified = f"{schema}.{table}"
        if action == "add" and kind == "table":
            statements.append(f"create table {qualified} ();" )
        elif action == "drop" and kind == "table":
            statements.append(f"drop table {qualified};")
        elif action == "add" and kind == "column":
            definition = _render_column(operation["after"])
            if definition is None:
                statements.append(f"-- MANUAL add column {qualified}.{operation['name']}")
            else:
                name = _quote_identifier(operation["name"])
                statements.append(f"alter table {qualified} add column {name} {definition};")
        elif action == "drop" and kind == "column":
            name = _quote_identifier(operation["name"])
            statements.append(f"alter table {qualified} drop column {name};")
        elif action == "add" and kind == "constraint":
            parts = operation["name"].split(":")
            columns = ", ".join(_quote_identifier(value) for value in parts[1].split(","))
            if len(parts) == 5 and parts[0] == "p":
                statements.append(f"alter table {qualified} add primary key ({columns});")
            elif len(parts) == 5 and parts[0] == "u":
                statements.append(f"alter table {qualified} add unique ({columns});")
            elif len(parts) == 5 and parts[0] == "f":
                remote = f"{_quote_identifier(parts[2])}.{_quote_identifier(parts[3])}"
                remote_columns = ", ".join(
                    _quote_identifier(value) for value in parts[4].split(",")
                )
                statements.append(
                    f"alter table {qualified} add foreign key ({columns}) "
                    f"references {remote} ({remote_columns});"
                )
            else:
                statements.append(f"-- MANUAL add constraint on {qualified}")
        else:
            name = operation["name"] or "<table>"
            statements.append(f"-- MANUAL {action} {kind} {qualified}.{name}")
    return "\n".join(statements) + ("\n" if statements else "")


def _write_generation_directory(
    output: Path, payload: dict[str, Any], artifact: Any
) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    if output.exists():
        raise FileExistsError(f"migration output already exists: {output}")
    temporary = Path(
        tempfile.mkdtemp(prefix=f".{output.name}.tmp-", dir=output.parent)
    )
    try:
        (temporary / "migration.bin").write_bytes(artifact.data)
        (temporary / "migration.sql").write_text(
            payload["review_sql"], encoding="utf-8"
        )
        (temporary / "migration.json").write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        temporary.rename(output)
    except BaseException:
        shutil.rmtree(temporary, ignore_errors=True)
        raise


async def _generate(namespace: argparse.Namespace, application: Any) -> dict[str, Any]:
    registries = getattr(application, "_orm_registries", {})
    registry = registries.get(namespace.database)
    if registry is None:
        known = ", ".join(sorted(registries)) or "none"
        raise ValueError(
            f"application has no ORM registry {namespace.database!r}; configured: {known}"
        )
    database = registry.database
    await database.start()
    workload = "read"
    try:
        try:
            database.pool(workload)
        except KeyError:
            workload = "write"
        connection = await database.acquire(workload)
        try:
            generation = await generate_single_plan(registry, connection)
        finally:
            await database.release(workload, connection)
    finally:
        await database.stop()
    operations = _unpack_named_plan(generation.plan.tape)
    payload: dict[str, Any] = {
        "format": "WMP1",
        "operation_count": generation.plan.operation_count,
        "desired_fingerprint": generation.desired_fingerprint.hex(),
        "actual_fingerprint": generation.actual_fingerprint.hex(),
        "operations": operations,
        "review_sql": _render_review_sql(operations),
    }
    if namespace.output is not None:
        if namespace.migration_id is None:
            raise ValueError("--output requires --migration-id")
        if not namespace.initial and namespace.parent is None:
            raise ValueError("--output requires exactly one of --initial or --parent")
        try:
            migration_id = bytes.fromhex(namespace.migration_id)
            parent = bytes(32) if namespace.initial else bytes.fromhex(namespace.parent)
        except ValueError as error:
            raise ValueError("migration and parent checksums must be hexadecimal") from error
        artifact = _build_native_artifact(
            migration_id=migration_id,
            parent_checksum=parent,
            source_fingerprint=generation.actual_fingerprint,
            target_fingerprint=generation.desired_fingerprint,
            operation_tape=generation.diff.tape,
        )
        output = Path(namespace.output)
        payload["artifact_checksum"] = artifact.checksum.hex()
        payload["migration_id"] = artifact.migration_id.hex()
        payload["parent_checksum"] = artifact.parent_checksum.hex()
        payload["output"] = str(output)
        _write_generation_directory(output, payload, artifact)
    return payload


def _read_artifacts(paths: list[str]) -> tuple[bytes, ...]:
    return tuple(Path(path).read_bytes() for path in paths)


async def _status(namespace: argparse.Namespace, application: Any) -> dict[str, Any]:
    artifact_data = _read_artifacts(namespace.artifacts)
    first = _load_native_artifact(artifact_data[0])
    if first.parent_checksum != bytes(32):
        raise ValueError("status requires a complete artifact chain beginning at the root")
    chain = _verify_native_chain(
        artifact_data,
        expected_parent=bytes(32),
        expected_source=first.source_fingerprint,
    )
    detection = await _detect(namespace, application)
    desired = bytes.fromhex(detection["desired_fingerprint"])
    actual = bytes.fromhex(detection["actual_fingerprint"])
    return {
        "current": actual == chain.target_fingerprint == desired,
        "catalog_matches_code": actual == desired,
        "artifacts_match_code": chain.target_fingerprint == desired,
        "migration_count": chain.migration_count,
        "chain_checksum": chain.checksum.hex(),
        "artifact_target_fingerprint": chain.target_fingerprint.hex(),
        "desired_fingerprint": desired.hex(),
        "actual_fingerprint": actual.hex(),
    }


def _show(namespace: argparse.Namespace) -> dict[str, Any]:
    artifact = _load_native_artifact(Path(namespace.artifact).read_bytes())
    operation_count = int.from_bytes(artifact.operation_tape[8:12], "little")
    payload = {
        "format": "WMA1",
        "migration_id": artifact.migration_id.hex(),
        "checksum": artifact.checksum.hex(),
        "parent_checksum": artifact.parent_checksum.hex(),
        "source_fingerprint": artifact.source_fingerprint.hex(),
        "target_fingerprint": artifact.target_fingerprint.hex(),
        "operation_count": operation_count,
        "artifact_bytes": len(artifact.data),
        "operation_tape_bytes": len(artifact.operation_tape),
    }
    return payload


def execute(
    namespace: argparse.Namespace,
    load_application: Callable[..., Any],
) -> int:
    """Execute one migration command without starting application lifespan."""
    exit_code = 0
    if namespace.migration_action in {"detect", "check"}:
        application = load_application(namespace.target, factory=namespace.factory)
        payload = asyncio.run(_detect(namespace, application))
        title = "schema is current" if payload["current"] else "schema drift detected"
        if namespace.migration_action == "check" and not payload["current"]:
            exit_code = 1
    elif namespace.migration_action == "generate":
        application = load_application(namespace.target, factory=namespace.factory)
        payload = asyncio.run(_generate(namespace, application))
        title = f"generated {payload['operation_count']} review operations"
    elif namespace.migration_action == "show":
        payload = _show(namespace)
        title = f"migration {payload['migration_id']}"
    elif namespace.migration_action == "status":
        application = load_application(namespace.target, factory=namespace.factory)
        payload = asyncio.run(_status(namespace, application))
        title = "migration state is current" if payload["current"] else "migration state differs"
        if not payload["current"]:
            exit_code = 1
    else:
        raise ValueError(f"unsupported migration command {namespace.migration_action!r}")
    if namespace.json:
        print(json.dumps(payload, sort_keys=True, separators=(",", ":")))
    else:
        print(title)
        for key, value in payload.items():
            if key not in {"current", "migration_id", "operations", "review_sql"}:
                print(f"  {key.replace('_', ' ')}: {value}")
        for operation in payload.get("operations", []):
            target = ".".join(
                part for part in (
                    operation["schema"], operation["table"], operation["name"]
                ) if part
            )
            print(f"  {operation['action']} {operation['kind']} {target}")
        if payload.get("review_sql"):
            print("\nreview SQL (not execution input):")
            print(payload["review_sql"], end="")
    return exit_code


__all__ = ["execute"]
