"""Provider-neutral model agents with governed tools and bounded execution."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ._agents.approvals import (
        ApprovalDenied,
        ApprovalExpired,
        ApprovalGrant,
        ApprovalMismatch,
        ApprovalRequest,
        ApprovalStore,
        InMemoryApprovalStore,
        PostgresApprovalStore,
    )
    from ._agents.artifacts import (
        AgentArtifact,
        AgentArtifactManager,
        ArtifactLimitExceeded,
        ArtifactTrust,
    )
    from ._agents.backplanes import (
        AnthropicMessagesBackplane,
        GeminiGenerateContentBackplane,
        OpenAICompatibleBackplane,
        OpenAIResponsesBackplane,
    )
    from ._agents.chat_approvals import ChatApprovalFlow
    from ._agents.core import (
        AgentBudgetExceeded,
        AgentCatalog,
        AgentConfigurationError,
        AgentInvocationContext,
        AgentProfile,
        AgentRuntime,
        BackplaneError,
        ModelBackplane,
        ModelMessage,
        ModelRequest,
        ModelResponseEvent,
        ModelTarget,
        ModelUsage,
        ToolSpecification,
    )
    from ._agents.durable import (
        DurableAgent,
        DurableEffectContext,
        DurableModelBackend,
        DurableToolExecutor,
        DurableTurn,
        EffectCheckpoint,
        EffectCheckpointStore,
        ModelResult,
        StaleAgentFence,
        ToolCall,
        UnknownModelOutcome,
        stable_tool_call_id,
        stable_turn_id,
    )
    from ._agents.enterprise_backplanes import AzureOpenAIBackplane
    from ._agents.federation import FederatedToolCatalog
    from ._agents.http_transport import HTTPClientTransport, MCPHTTPClientTransport
    from ._agents.memory import (
        AssembledContext,
        ContextAssembler,
        MemoryRecord,
        MemoryStore,
        MemoryTrust,
    )
    from ._agents.observability import (
        AgentCapturePolicy,
        AgentObservability,
        AgentObservation,
        AgentObserver,
        AgentOutcome,
        AgentUsage,
        CapturedAgentPayload,
    )
    from ._agents.remote_mcp import (
        MCPHTTPResponse,
        MCPHTTPTransport,
        MCPInvocationAudit,
        MCPInvocationObserver,
        MCPRemoteError,
        MCPRemoteScopeError,
        MCPTokenProvider,
        MCPToolCatalogDrift,
        MCPToolLimitExceeded,
        RemoteMCPClient,
        RemoteMCPToolCatalog,
        RemoteMCPToolSet,
        UnknownToolOutcome,
    )
    from ._agents.routing import ModelCandidate, ModelRoutePolicy, RoutedBackplane
    from ._agents.tools import MCPToolCatalog

__all__ = [
    "AgentBudgetExceeded",
    "AgentArtifact",
    "AgentArtifactManager",
    "AgentCapturePolicy",
    "AgentCatalog",
    "AgentConfigurationError",
    "AgentInvocationContext",
    "AgentObservation",
    "AgentObservability",
    "AgentObserver",
    "AgentOutcome",
    "AgentProfile",
    "AgentRuntime",
    "AgentUsage",
    "AnthropicMessagesBackplane",
    "ApprovalDenied",
    "ApprovalExpired",
    "ApprovalGrant",
    "ApprovalMismatch",
    "ApprovalRequest",
    "ApprovalStore",
    "ArtifactLimitExceeded",
    "ArtifactTrust",
    "AssembledContext",
    "AzureOpenAIBackplane",
    "BackplaneError",
    "ContextAssembler",
    "CapturedAgentPayload",
    "ChatApprovalFlow",
    "DurableAgent",
    "DurableEffectContext",
    "DurableModelBackend",
    "DurableToolExecutor",
    "DurableTurn",
    "EffectCheckpoint",
    "EffectCheckpointStore",
    "GeminiGenerateContentBackplane",
    "FederatedToolCatalog",
    "HTTPClientTransport",
    "InMemoryApprovalStore",
    "MemoryRecord",
    "MemoryStore",
    "MemoryTrust",
    "MCPToolCatalog",
    "MCPHTTPResponse",
    "MCPHTTPClientTransport",
    "MCPHTTPTransport",
    "MCPInvocationAudit",
    "MCPInvocationObserver",
    "MCPRemoteError",
    "MCPRemoteScopeError",
    "MCPTokenProvider",
    "MCPToolCatalogDrift",
    "MCPToolLimitExceeded",
    "ModelBackplane",
    "ModelCandidate",
    "ModelMessage",
    "ModelRequest",
    "ModelResult",
    "ModelResponseEvent",
    "ModelRoutePolicy",
    "ModelTarget",
    "ModelUsage",
    "OpenAICompatibleBackplane",
    "OpenAIResponsesBackplane",
    "PostgresApprovalStore",
    "RemoteMCPClient",
    "RemoteMCPToolCatalog",
    "RemoteMCPToolSet",
    "RoutedBackplane",
    "StaleAgentFence",
    "ToolCall",
    "ToolSpecification",
    "UnknownModelOutcome",
    "UnknownToolOutcome",
    "stable_tool_call_id",
    "stable_turn_id",
]

_EXPORTS = {
    "AgentArtifact": "artifacts",
    "AgentArtifactManager": "artifacts",
    "AgentBudgetExceeded": "core",
    "AgentCapturePolicy": "observability",
    "AgentCatalog": "core",
    "AgentConfigurationError": "core",
    "AgentInvocationContext": "core",
    "AgentObservation": "observability",
    "AgentObservability": "observability",
    "AgentObserver": "observability",
    "AgentOutcome": "observability",
    "AgentProfile": "core",
    "AgentRuntime": "core",
    "AgentUsage": "observability",
    "AnthropicMessagesBackplane": "backplanes",
    "ApprovalDenied": "approvals",
    "ApprovalExpired": "approvals",
    "ApprovalGrant": "approvals",
    "ApprovalMismatch": "approvals",
    "ApprovalRequest": "approvals",
    "ApprovalStore": "approvals",
    "ArtifactLimitExceeded": "artifacts",
    "ArtifactTrust": "artifacts",
    "AssembledContext": "memory",
    "AzureOpenAIBackplane": "enterprise_backplanes",
    "BackplaneError": "core",
    "ContextAssembler": "memory",
    "CapturedAgentPayload": "observability",
    "ChatApprovalFlow": "chat_approvals",
    "DurableAgent": "durable",
    "DurableEffectContext": "durable",
    "DurableModelBackend": "durable",
    "DurableToolExecutor": "durable",
    "DurableTurn": "durable",
    "EffectCheckpoint": "durable",
    "EffectCheckpointStore": "durable",
    "GeminiGenerateContentBackplane": "backplanes",
    "FederatedToolCatalog": "federation",
    "HTTPClientTransport": "http_transport",
    "InMemoryApprovalStore": "approvals",
    "MemoryRecord": "memory",
    "MemoryStore": "memory",
    "MemoryTrust": "memory",
    "MCPToolCatalog": "tools",
    "MCPHTTPResponse": "remote_mcp",
    "MCPHTTPClientTransport": "http_transport",
    "MCPHTTPTransport": "remote_mcp",
    "MCPInvocationAudit": "remote_mcp",
    "MCPInvocationObserver": "remote_mcp",
    "MCPRemoteError": "remote_mcp",
    "MCPRemoteScopeError": "remote_mcp",
    "MCPTokenProvider": "remote_mcp",
    "MCPToolCatalogDrift": "remote_mcp",
    "MCPToolLimitExceeded": "remote_mcp",
    "ModelBackplane": "core",
    "ModelCandidate": "routing",
    "ModelMessage": "core",
    "ModelRequest": "core",
    "ModelResponseEvent": "core",
    "ModelRoutePolicy": "routing",
    "ModelResult": "durable",
    "ModelTarget": "core",
    "ModelUsage": "core",
    "OpenAICompatibleBackplane": "backplanes",
    "OpenAIResponsesBackplane": "backplanes",
    "PostgresApprovalStore": "approvals",
    "RemoteMCPClient": "remote_mcp",
    "RemoteMCPToolCatalog": "remote_mcp",
    "RemoteMCPToolSet": "remote_mcp",
    "RoutedBackplane": "routing",
    "StaleAgentFence": "durable",
    "ToolCall": "durable",
    "ToolSpecification": "core",
    "UnknownModelOutcome": "durable",
    "UnknownToolOutcome": "remote_mcp",
    "stable_tool_call_id": "durable",
    "stable_turn_id": "durable",
}


def __getattr__(name: str) -> Any:
    module = _EXPORTS.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    from importlib import import_module

    loaded = import_module(f"._agents.{module}", __package__)
    namespace = globals()
    for export, owner in _EXPORTS.items():
        if owner == module:
            namespace[export] = getattr(loaded, export)
    return namespace[name]


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__})
