"""Strict RFC 9209 Proxy-Status field members."""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass, field

from ._structured_fields import BareItem, Item, Token, serialize_item

__all__ = ["ProxyStatus"]

_URI_UNRESERVED = frozenset(b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~")


def _text(value: str, name: str, *, non_empty: bool = False) -> str:
    if not isinstance(value, str):
        raise TypeError(f"{name} must be str, not {type(value).__name__}")
    if non_empty and not value:
        raise ValueError(
            f"{name} must be a non-empty RFC 9651 String or Token containing only printable ASCII"
        )
    try:
        serialize_item(Item(value))
    except ValueError as error:
        if non_empty:
            raise ValueError(
                f"{name} must be a non-empty RFC 9651 String or Token "
                "containing only printable ASCII"
            ) from error
        raise ValueError(
            f"{name} must contain only printable ASCII as an RFC 9651 String"
        ) from error
    return value


def _token_or_string(value: str, name: str, *, non_empty: bool = True) -> str | Token:
    value = _text(value, name, non_empty=non_empty)
    try:
        return Token(value)
    except ValueError:
        return value


def _token(value: str, name: str) -> Token:
    _text(value, name, non_empty=True)
    try:
        return Token(value)
    except ValueError as error:
        raise ValueError(f"{name} must be an RFC 9651 Token") from error


def _encode_dns_alias(alias: str) -> str:
    if not isinstance(alias, str):
        raise TypeError(f"next_hop_aliases entries must be str, not {type(alias).__name__}")
    if not alias:
        raise ValueError("next_hop_aliases entries must not be empty DNS names")
    try:
        alias.encode("ascii")
    except UnicodeEncodeError as error:
        raise ValueError(
            "next_hop_aliases entries must be ASCII DNS names; convert Unicode names "
            "to IDNA A-labels"
        ) from error

    labels: list[bytes] = []
    label = bytearray()
    index = 0
    while index < len(alias):
        character = alias[index]
        if character == "\\":
            if index + 1 >= len(alias) or alias[index + 1] not in ".\\":
                raise ValueError(
                    f"next_hop_aliases entry {alias!r} has an invalid DNS escape; "
                    "only '\\.' and '\\\\' are valid"
                )
            label.append(ord(alias[index + 1]))
            index += 2
            continue
        if character == ".":
            if not label:
                if index == len(alias) - 1 and labels:
                    index += 1
                    break
                raise ValueError(f"next_hop_aliases entry {alias!r} has an empty DNS label")
            labels.append(bytes(label))
            label.clear()
            index += 1
            continue
        label.append(ord(character))
        index += 1
    if label:
        labels.append(bytes(label))
    if not labels:
        raise ValueError(f"next_hop_aliases entry {alias!r} must contain a DNS name")
    for part in labels:
        if len(part) > 63:
            raise ValueError(
                f"next_hop_aliases entry {alias!r} has a DNS label longer than 63 octets"
            )
    if sum(len(part) + 1 for part in labels) + 1 > 255:
        raise ValueError(f"next_hop_aliases entry {alias!r} exceeds the 255-octet DNS limit")

    encoded_labels: list[str] = []
    for part in labels:
        encoded = []
        for byte in part:
            if byte == 0x2E:
                encoded.append("%5C.")
            elif byte == 0x5C:
                encoded.append("%5C%5C")
            elif byte in _URI_UNRESERVED:
                encoded.append(chr(byte))
            else:
                encoded.append(f"%{byte:02X}")
        encoded_labels.append("".join(encoded))
    return ".".join(encoded_labels)


def _aliases(value: Iterable[str]) -> tuple[tuple[str, ...], str]:
    if isinstance(value, str | bytes):
        raise TypeError("next_hop_aliases must be an iterable of DNS names, not one string")
    try:
        aliases = tuple(value)
    except TypeError as error:
        raise TypeError("next_hop_aliases must be an iterable of DNS names") from error
    return aliases, ",".join(_encode_dns_alias(alias) for alias in aliases)


@dataclass(frozen=True, slots=True)
class ProxyStatus:
    """One RFC 9209 Proxy-Status list member generated by an intermediary.

    Construction validates every value and precomputes the immutable wire
    representation. `to_header()` returns one list member, without a leading or
    trailing comma, so an intermediary can append it to an existing field.
    """

    proxy: str
    error: str | None = None
    next_hop: str | None = None
    next_hop_aliases: Iterable[str] | None = None
    next_protocol: str | bytes | None = None
    received_status: int | None = None
    details: str | None = None
    _header: bytes = field(init=False, repr=False, compare=False)

    def __post_init__(self) -> None:
        proxy = _token_or_string(self.proxy, "proxy")
        parameters: dict[str, BareItem] = {}
        if self.error is not None:
            parameters["error"] = _token(self.error, "error")
        if self.next_hop is not None:
            parameters["next-hop"] = _token_or_string(self.next_hop, "next_hop")
        if self.next_hop_aliases is not None:
            aliases, encoded_aliases = _aliases(self.next_hop_aliases)
            object.__setattr__(self, "next_hop_aliases", aliases)
            parameters["next-hop-aliases"] = encoded_aliases
        if self.next_protocol is not None:
            protocol = self.next_protocol
            if isinstance(protocol, str):
                parameters["next-protocol"] = _token(protocol, "next_protocol")
            elif isinstance(protocol, bytes):
                try:
                    parameters["next-protocol"] = Token(protocol.decode("ascii"))
                except UnicodeDecodeError, ValueError:
                    parameters["next-protocol"] = protocol
            else:
                raise TypeError(
                    f"next_protocol must be str or bytes, not {type(protocol).__name__}"
                )
        if self.received_status is not None:
            received_status = self.received_status
            if type(received_status) is not int:
                raise TypeError(
                    f"received_status must be int, not {type(received_status).__name__}"
                )
            if not 100 <= received_status <= 599:
                raise ValueError("received_status must be an HTTP status code from 100 to 599")
            parameters["received-status"] = received_status
        if self.details is not None:
            parameters["details"] = _text(self.details, "details")
        object.__setattr__(self, "_header", serialize_item(Item(proxy, parameters)))

    def to_header(self) -> bytes:
        """Return this entry as one canonical structured-field list member."""
        return self._header
