"""The TypeScript renderer for typegen.

This module renders already-normalized, prevalidated tuples -- never the
semantic dataclasses and never live Python objects. That keeps the boundary to
an optional native renderer explicit and makes parity fixtures compact. Output
assembly is linear: a list builder with one final join, no output-proportional
string concatenation.

**This stays Python.** The "benchmark decision" `render.py` defers to has been
made: rendering a client is a cold path reached from `wreath typegen`, run by a
developer occasionally rather than by a request, and the assembly above is
already linear with a single join. `select_renderers` keeps its seam because it
costs nothing, but a missing `_core.typegen_render_*` is not a gap.

Normalized tuple contract (version `TYPEGEN_CONTRACT`):

`type_tuple`
    ``(kind: str, name: str | None, args: tuple[type_tuple, ...],
      literals: tuple[str | int | float | bool | None, ...])``

`declaration` (an interface)
    `(name: str, fields: tuple[(wire_name: str, type_tuple, required: bool), ...])`

`operation` (a client method)
    `(id, method, path, params, request_body, request_media, response)` where
    `params` is `((client_name, wire_name, location, type_tuple, required), ...)`,
    `request_body` is a `type_tuple` or `None`, and `response` is a
    `type_tuple`.
"""

from __future__ import annotations

import re
from typing import Any

from ._names import pascal as _pascal

TYPEGEN_CONTRACT = 1
GENERATOR_HEADER = (
    "// Generated by wreath typegen. Do not edit.\n"
    "// This file is owned by wreath-typegen.json; edits are overwritten.\n"
)

_IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def _ts_literal(value: Any) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        return '"' + _escape(value) + '"'
    return repr(value) if isinstance(value, float) else str(value)


def _escape(text: str) -> str:
    out: list[str] = []
    for char in text:
        if char == "\\":
            out.append("\\\\")
        elif char == '"':
            out.append('\\"')
        elif char == "\n":
            out.append("\\n")
        elif char == "\r":
            out.append("\\r")
        elif char == "\t":
            out.append("\\t")
        elif ord(char) < 0x20:
            out.append(f"\\u{ord(char):04x}")
        else:
            out.append(char)
    return "".join(out)


#: OpenAPI `format` -> the TypeScript alias emitted for it. Aliases rather than
#: branded types on purpose: `IsoDateTime = string` stays assignable from a
#: plain string, so nothing an existing client does breaks, while the field
#: still reads as a timestamp in an editor. A branded type would be stricter and
#: would force every caller to cast, which is a bigger promise than a generated
#: client should make on its own.
_ISO_ALIASES: dict[str, str] = {
    "date-time": "IsoDateTime",
    "date": "IsoDate",
}

_ISO_ALIAS_SOURCE = {
    "IsoDateTime": (
        "/** ISO-8601 timestamp with a UTC offset, e.g.\n"
        ' *  "2026-07-26T09:30:00+00:00". */\n'
        "export type IsoDateTime = string;"
    ),
    "IsoDate": ('/** ISO-8601 calendar date, e.g. "2026-07-26". */\nexport type IsoDate = string;'),
}


def _aliases_used(declarations: tuple[Any, ...]) -> list[str]:
    """Which ISO aliases these declarations mention, in declaration order.

    Walked rather than string-matched so an API with no timestamps emits no
    aliases at all, and one with only dates does not carry a datetime alias it
    never uses.
    """
    found: list[str] = []

    def visit(node: tuple[Any, ...]) -> None:
        kind, name, args, _literals = node
        if kind == "string":
            alias = _ISO_ALIASES.get(name)
            if alias is not None and alias not in found:
                found.append(alias)
        for arg in args or ():
            visit(arg)

    for _name, fields in declarations:
        for _wire_name, type_tuple, _required in fields:
            visit(type_tuple)
    return found


def ts_type(node: tuple[Any, ...]) -> str:
    kind, name, args, literals = node
    if kind == "unknown":
        return "unknown"
    if kind == "null":
        return "null"
    if kind == "boolean":
        return "boolean"
    if kind in ("integer", "number"):
        return "number"
    if kind == "string":
        # A tagged string keeps its meaning in the generated types: an alias is
        # still assignable from `string`, so nothing breaks, but a reader (and
        # an editor's hover) can see that the field is a timestamp rather than
        # free text. `_ISO_ALIASES` declares them in the emitted module.
        return _ISO_ALIASES.get(name, "string")
    if kind == "reference":
        return name  # type: ignore[return-value]
    if kind == "array":
        inner = ts_type(args[0]) if args else "unknown"
        needs_parens = args and args[0][0] in ("union", "literal")
        return f"({inner})[]" if needs_parens else f"{inner}[]"
    if kind == "tuple":
        return "[" + ", ".join(ts_type(arg) for arg in args) + "]"
    if kind == "record":
        value = ts_type(args[0]) if args else "unknown"
        return f"Record<string, {value}>"
    if kind == "union":
        return " | ".join(ts_type(arg) for arg in args)
    if kind == "literal":
        return " | ".join(_ts_literal(value) for value in literals)
    if kind == "coordinate":
        # Named components, not `[number, number]`: a tuple type-checks with the
        # arguments the wrong way round, which is the transposition the whole
        # declaration exists to make unrepresentable.
        return "{ lat: number; lon: number }"
    if kind == "page":
        # Structural, not a named `Page<T>` alias. The Python target imports
        # `wreath.pagination.Page` because there is a real type to *be*; a
        # TypeScript client is standalone, so a named alias would have to be
        # declared somewhere, and a preamble means one more thing two emitters
        # have to agree on for no gain. Inline always compiles and cannot
        # drift.
        inner = ts_type(args[0]) if args else "unknown"
        return "{ items: readonly " + inner + "[]; total: number; page: number; size: number }"
    raise ValueError(
        f"no TypeScript type for TypeKind {kind!r}. A kind added to "
        "`wreath.typegen.model.TypeKind` must be rendered here and in "
        "`wreath.openapi._openapi_schema`; returning `unknown` instead would emit a "
        "client that compiles and is wrong, and report success."
    )


def _property_key(wire_name: str) -> str:
    return wire_name if _IDENTIFIER.match(wire_name) else '"' + _escape(wire_name) + '"'


def _render_interface(name: str, fields: tuple[Any, ...]) -> list[str]:
    lines = [f"export interface {name} {{"]
    for wire_name, type_tuple, required in fields:
        optional = "" if required else "?"
        lines.append(f"  {_property_key(wire_name)}{optional}: {ts_type(type_tuple)};")
    lines.append("}")
    return lines


def render_models(declarations: tuple[Any, ...], flags: int = 0) -> bytes:
    """Render the models module: data-model and per-operation parameter
    interfaces, in the order supplied (Python owns ordering)."""
    parts: list[str] = [GENERATOR_HEADER]
    blocks = [_ISO_ALIAS_SOURCE[alias] for alias in _aliases_used(declarations)]
    blocks += ["\n".join(_render_interface(name, fields)) for name, fields in declarations]
    parts.append("\n\n".join(blocks) + ("\n" if blocks else ""))
    return "".join(parts).encode("utf-8")


_CLIENT_PRELUDE = """\
export interface WreathClientOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  headers?: HeadersInit | (() => HeadersInit | Promise<HeadersInit>);
}

export class WreathApiError extends Error {
  readonly status: number;
  readonly statusText: string;
  readonly headers: Headers;
  readonly body: unknown;

  constructor(status: number, statusText: string, headers: Headers, body: unknown) {
    super(`Wreath API error ${status} ${statusText}`);
    this.name = "WreathApiError";
    this.status = status;
    this.statusText = statusText;
    this.headers = headers;
    this.body = body;
  }
}

async function resolveHeaders(
  source: WreathClientOptions["headers"],
): Promise<HeadersInit | undefined> {
  return typeof source === "function" ? await source() : source;
}

async function decodeBody(response: Response): Promise<unknown> {
  const contentType = response.headers.get("content-type") ?? "";
  if (contentType.includes("application/json")) {
    return await response.json();
  }
  return await response.text();
}
"""


def _method_lines(operation: tuple[Any, ...]) -> list[str]:
    op_id, method, path, params, request_body, request_media, response = operation
    path_params = [p for p in params if p[2] == "path"]
    query_params = [p for p in params if p[2] == "query"]
    header_params = [p for p in params if p[2] == "header"]
    has_params_object = bool(path_params or query_params or header_params)
    param_interface = _pascal(op_id) + "Parameters"

    signature_parts: list[str] = []
    if has_params_object:
        signature_parts.append(f"parameters: {param_interface}")
    if request_body is not None:
        signature_parts.append(f"body: {ts_type(request_body)}")
    signature_parts.append("init?: RequestInit")
    signature = ", ".join(signature_parts)
    return_type = ts_type(response)

    body: list[str] = [f"    async {op_id}({signature}): Promise<{return_type}> {{"]

    # Build the path with encodeURIComponent on each substituted value.
    path_expr = _path_expression(path, path_params)
    body.append(f"      const url = new URL(`${{this.baseUrl}}{path_expr}`);")
    for client_name, wire_name, _location, _type_tuple, _required in query_params:
        body.append(
            f"      if (parameters.{client_name} !== undefined) "
            f'url.searchParams.set("{_escape(wire_name)}", '
            f"String(parameters.{client_name}));"
        )
    body.append("      const headers = new Headers(await resolveHeaders(this.headers));")
    for client_name, wire_name, _location, _type_tuple, required in header_params:
        guard = "" if required else f"if (parameters.{client_name} !== undefined) "
        body.append(
            f'      {guard}headers.set("{_escape(wire_name)}", String(parameters.{client_name}));'
        )
    request_init: list[str] = [f'method: "{method}"']
    if request_body is not None:
        if request_media == "application/json":
            body.append('      headers.set("content-type", "application/json");')
            request_init.append("body: JSON.stringify(body)")
        else:
            request_init.append("body: body as BodyInit")
    request_init.append("headers")
    body.append(
        "      const response = await this.fetchImpl(url, { "
        + ", ".join(request_init)
        + ", ...init });"
    )
    body.append("      if (!response.ok) {")
    body.append("        throw new WreathApiError(")
    body.append("          response.status,")
    body.append("          response.statusText,")
    body.append("          response.headers,")
    body.append("          await decodeBody(response).catch(() => undefined),")
    body.append("        );")
    body.append("      }")
    if return_type == "unknown":
        body.append("      return (await decodeBody(response)) as unknown;")
    else:
        body.append(f"      return (await decodeBody(response)) as {return_type};")
    body.append("    }")
    return body


def _path_expression(path: str, path_params: list[Any]) -> str:
    wire_to_client = {p[1]: p[0] for p in path_params}
    out: list[str] = []
    for segment in path.split("/"):
        if not segment:
            continue
        if segment.startswith("{") and segment.endswith("}"):
            wire = segment[1:-1]
            client = wire_to_client.get(wire, wire)
            out.append("/${encodeURIComponent(String(parameters." + client + "))}")
        else:
            out.append("/" + segment)
    return "".join(out) or "/"


def render_client(payload: tuple[Any, ...], flags: int = 0) -> bytes:
    """`payload` is `(import_names, operations)`. `import_names` are the
    model/parameter interface names to import as types from `./models`."""
    import_names, operations = payload
    parts: list[str] = [GENERATOR_HEADER]
    if import_names:
        joined = ",\n  ".join(import_names)
        parts.append(f'\nimport type {{\n  {joined},\n}} from "./models";\n')
    parts.extend(["\n", _CLIENT_PRELUDE, "\n"])
    parts.append("export class WreathClient {\n")
    parts.append("  private readonly baseUrl: string;\n")
    parts.append("  private readonly fetchImpl: typeof globalThis.fetch;\n")
    parts.append('  private readonly headers: WreathClientOptions["headers"];\n\n')
    parts.append("  constructor(options: WreathClientOptions) {\n")
    parts.append('    this.baseUrl = options.baseUrl.replace(/\\/$/, "");\n')
    parts.append("    this.fetchImpl = options.fetch ?? globalThis.fetch;\n")
    parts.append("    this.headers = options.headers;\n")
    parts.append("  }\n\n")
    method_blocks = ["\n".join(_method_lines(operation)) for operation in operations]
    parts.append("\n\n".join(method_blocks))
    parts.append("\n}\n\n")
    parts.append(
        "export function createWreathClient(options: WreathClientOptions): WreathClient {\n"
    )
    parts.append("  return new WreathClient(options);\n")
    parts.append("}\n")
    return "".join(parts).encode("utf-8")


__all__ = [
    "GENERATOR_HEADER",
    "TYPEGEN_CONTRACT",
    "render_client",
    "render_models",
    "ts_type",
]
